package com.yunxin.mapper;

import com.yunxin.entity.CaMerchants;
import com.yunxin.entity.CaMerchantsExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface CaMerchantsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Merchants
     *
     * @mbggenerated Thu Mar 02 13:37:03 CST 2017
     */
    @SelectProvider(type=CaMerchantsSqlProvider.class, method="countByExample")
    int countByExample(CaMerchantsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Merchants
     *
     * @mbggenerated Thu Mar 02 13:37:03 CST 2017
     */
    @DeleteProvider(type=CaMerchantsSqlProvider.class, method="deleteByExample")
    int deleteByExample(CaMerchantsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Merchants
     *
     * @mbggenerated Thu Mar 02 13:37:03 CST 2017
     */
    @Delete({
        "delete from CA_Merchants",
        "where MerId = #{merid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String merid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Merchants
     *
     * @mbggenerated Thu Mar 02 13:37:03 CST 2017
     */
    @Insert({
        "insert into CA_Merchants (MerId, MerchantName, ",
        "SecretKey, PublicKey, ",
        "DataCreateTime, DataLastChangeTime, ",
        "ValidatedRequestIPAddress)",
        "values (#{merid,jdbcType=VARCHAR}, #{merchantname,jdbcType=NVARCHAR}, ",
        "#{secretkey,jdbcType=VARCHAR}, #{publickey,jdbcType=NVARCHAR}, ",
        "#{datacreatetime,jdbcType=TIMESTAMP}, #{datalastchangetime,jdbcType=TIMESTAMP}, ",
        "#{validatedrequestipaddress,jdbcType=VARCHAR})"
    })
    int insert(CaMerchants record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Merchants
     *
     * @mbggenerated Thu Mar 02 13:37:03 CST 2017
     */
    @InsertProvider(type=CaMerchantsSqlProvider.class, method="insertSelective")
    int insertSelective(CaMerchants record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Merchants
     *
     * @mbggenerated Thu Mar 02 13:37:03 CST 2017
     */
    @SelectProvider(type=CaMerchantsSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="MerId", property="merid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="MerchantName", property="merchantname", jdbcType=JdbcType.NVARCHAR),
        @Result(column="SecretKey", property="secretkey", jdbcType=JdbcType.VARCHAR),
        @Result(column="PublicKey", property="publickey", jdbcType=JdbcType.NVARCHAR),
        @Result(column="DataCreateTime", property="datacreatetime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="DataLastChangeTime", property="datalastchangetime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="ValidatedRequestIPAddress", property="validatedrequestipaddress", jdbcType=JdbcType.VARCHAR)
    })
    List<CaMerchants> selectByExample(CaMerchantsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Merchants
     *
     * @mbggenerated Thu Mar 02 13:37:03 CST 2017
     */
    @Select({
        "select",
        "MerId, MerchantName, SecretKey, PublicKey, DataCreateTime, DataLastChangeTime, ",
        "ValidatedRequestIPAddress",
        "from CA_Merchants",
        "where MerId = #{merid,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="MerId", property="merid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="MerchantName", property="merchantname", jdbcType=JdbcType.NVARCHAR),
        @Result(column="SecretKey", property="secretkey", jdbcType=JdbcType.VARCHAR),
        @Result(column="PublicKey", property="publickey", jdbcType=JdbcType.NVARCHAR),
        @Result(column="DataCreateTime", property="datacreatetime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="DataLastChangeTime", property="datalastchangetime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="ValidatedRequestIPAddress", property="validatedrequestipaddress", jdbcType=JdbcType.VARCHAR)
    })
    CaMerchants selectByPrimaryKey(String merid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Merchants
     *
     * @mbggenerated Thu Mar 02 13:37:03 CST 2017
     */
    @UpdateProvider(type=CaMerchantsSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") CaMerchants record, @Param("example") CaMerchantsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Merchants
     *
     * @mbggenerated Thu Mar 02 13:37:03 CST 2017
     */
    @UpdateProvider(type=CaMerchantsSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") CaMerchants record, @Param("example") CaMerchantsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Merchants
     *
     * @mbggenerated Thu Mar 02 13:37:03 CST 2017
     */
    @UpdateProvider(type=CaMerchantsSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(CaMerchants record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Merchants
     *
     * @mbggenerated Thu Mar 02 13:37:03 CST 2017
     */
    @Update({
        "update CA_Merchants",
        "set MerchantName = #{merchantname,jdbcType=NVARCHAR},",
          "SecretKey = #{secretkey,jdbcType=VARCHAR},",
          "PublicKey = #{publickey,jdbcType=NVARCHAR},",
          "DataCreateTime = #{datacreatetime,jdbcType=TIMESTAMP},",
          "DataLastChangeTime = #{datalastchangetime,jdbcType=TIMESTAMP},",
          "ValidatedRequestIPAddress = #{validatedrequestipaddress,jdbcType=VARCHAR}",
        "where MerId = #{merid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(CaMerchants record);
}