package com.yunxin.mapper;

import com.yunxin.entity.CaProduct;
import com.yunxin.entity.CaProductExample;
import com.yunxin.entity.CaProductExample.Criteria;
import com.yunxin.entity.CaProductExample.Criterion;

import java.util.List;
import java.util.Map;

import static org.apache.ibatis.jdbc.SqlBuilder.*;

public class CaProductSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Product
     *
     * @mbggenerated Thu Mar 02 13:37:03 CST 2017
     */
    public String countByExample(CaProductExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("CA_Product");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Product
     *
     * @mbggenerated Thu Mar 02 13:37:03 CST 2017
     */
    public String deleteByExample(CaProductExample example) {
        BEGIN();
        DELETE_FROM("CA_Product");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Product
     *
     * @mbggenerated Thu Mar 02 13:37:03 CST 2017
     */
    public String insertSelective(CaProduct record) {
        BEGIN();
        INSERT_INTO("CA_Product");
        
        if (record.getProductcode() != null) {
            VALUES("ProductCode", "#{productcode,jdbcType=NVARCHAR}");
        }
        
        if (record.getProductname() != null) {
            VALUES("ProductName", "#{productname,jdbcType=NVARCHAR}");
        }
        
        if (record.getInvestmentindustry() != null) {
            VALUES("InvestmentIndustry", "#{investmentindustry,jdbcType=NVARCHAR}");
        }
        
        if (record.getIndustrydetail() != null) {
            VALUES("IndustryDetail", "#{industrydetail,jdbcType=NVARCHAR}");
        }
        
        if (record.getIscycleloan() != null) {
            VALUES("IsCycleLoan", "#{iscycleloan,jdbcType=NVARCHAR}");
        }
        
        if (record.getPenaltyinterestcomputing() != null) {
            VALUES("PenaltyInterestComputing", "#{penaltyinterestcomputing,jdbcType=NVARCHAR}");
        }
        
        if (record.getLoaninterestcomputing() != null) {
            VALUES("LoanInterestComputing", "#{loaninterestcomputing,jdbcType=NVARCHAR}");
        }
        
        if (record.getPenaltyinterest() != null) {
            VALUES("PenaltyInterest", "#{penaltyinterest,jdbcType=DECIMAL}");
        }
        
        if (record.getPledgeremind() != null) {
            VALUES("PledgeRemind", "#{pledgeremind,jdbcType=NVARCHAR}");
        }
        
        if (record.getInterestratetype() != null) {
            VALUES("InterestRateType", "#{interestratetype,jdbcType=NVARCHAR}");
        }
        
        if (record.getInteresttype() != null) {
            VALUES("InterestType", "#{interesttype,jdbcType=NVARCHAR}");
        }
        
        if (record.getPartnercode() != null) {
            VALUES("PartnerCode", "#{partnercode,jdbcType=NVARCHAR}");
        }
        
        if (record.getCheckbrfrauds() != null) {
            VALUES("CheckBRFrauds", "#{checkbrfrauds,jdbcType=VARCHAR}");
        }
        
        if (record.getDatacreatetime() != null) {
            VALUES("DataCreateTime", "#{datacreatetime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getDatalastchangetime() != null) {
            VALUES("DataLastChangeTime", "#{datalastchangetime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getPaymentaccountno() != null) {
            VALUES("PaymentAccountNo", "#{paymentaccountno,jdbcType=VARCHAR}");
        }
        
        if (record.getPaymentchannel() != null) {
            VALUES("PaymentChannel", "#{paymentchannel,jdbcType=INTEGER}");
        }
        
        if (record.getPrefixloancontractnumber() != null) {
            VALUES("PrefixLoanContractNumber", "#{prefixloancontractnumber,jdbcType=VARCHAR}");
        }
        
        if (record.getIsneedhandidcardimage() != null) {
            VALUES("IsNeedHandIDCardImage", "#{isneedhandidcardimage,jdbcType=INTEGER}");
        }
        
        if (record.getIsneedbankcardimage() != null) {
            VALUES("IsNeedBankCardImage", "#{isneedbankcardimage,jdbcType=INTEGER}");
        }
        
        if (record.getIsneedemail() != null) {
            VALUES("IsNeedEmail", "#{isneedemail,jdbcType=INTEGER}");
        }
        
        if (record.getIsneedplatproductname() != null) {
            VALUES("IsNeedPlatProductName", "#{isneedplatproductname,jdbcType=INTEGER}");
        }
        
        if (record.getIsneedloanpurpose() != null) {
            VALUES("IsNeedLoanPurpose", "#{isneedloanpurpose,jdbcType=INTEGER}");
        }
        
        if (record.getIsneedplatrating() != null) {
            VALUES("IsNeedPlatRating", "#{isneedplatrating,jdbcType=INTEGER}");
        }
        
        if (record.getIsneedidcardvalidatedate() != null) {
            VALUES("IsNeedIDCardValidateDate", "#{isneedidcardvalidatedate,jdbcType=INTEGER}");
        }
        
        if (record.getIsneedemergencycontact() != null) {
            VALUES("IsNeedEmergencyContact", "#{isneedemergencycontact,jdbcType=INTEGER}");
        }
        
        if (record.getIsneedmaritalinfo() != null) {
            VALUES("IsNeedMaritalInfo", "#{isneedmaritalinfo,jdbcType=INTEGER}");
        }
        
        if (record.getIsneedpledge() != null) {
            VALUES("IsNeedPledge", "#{isneedpledge,jdbcType=INTEGER}");
        }
        
        if (record.getIsneedguarantee() != null) {
            VALUES("IsNeedGuarantee", "#{isneedguarantee,jdbcType=INTEGER}");
        }
        
        if (record.getIsneedentrust() != null) {
            VALUES("IsNeedEntrust", "#{isneedentrust,jdbcType=INTEGER}");
        }
        
        if (record.getRepayschedulesource() != null) {
            VALUES("RePayScheduleSource", "#{repayschedulesource,jdbcType=NVARCHAR}");
        }
        
        if (record.getIsrepayscheduleregular() != null) {
            VALUES("IsRePayScheduleRegular", "#{isrepayscheduleregular,jdbcType=INTEGER}");
        }
        
        if (record.getIsneedapprove() != null) {
            VALUES("IsNeedApprove", "#{isneedapprove,jdbcType=INTEGER}");
        }
        
        if (record.getAdvancedaysforallrepay() != null) {
            VALUES("AdvanceDaysForAllRepay", "#{advancedaysforallrepay,jdbcType=INTEGER}");
        }
        
        if (record.getApplypaymentsouce() != null) {
            VALUES("ApplyPaymentSouce", "#{applypaymentsouce,jdbcType=INTEGER}");
        }
        
        if (record.getTrustaccoutno() != null) {
            VALUES("TrustAccoutNo", "#{trustaccoutno,jdbcType=VARCHAR}");
        }
        
        if (record.getBorroweragebegin() != null) {
            VALUES("BorrowerAgeBegin", "#{borroweragebegin,jdbcType=INTEGER}");
        }
        
        if (record.getBorrowerageend() != null) {
            VALUES("BorrowerAgeEnd", "#{borrowerageend,jdbcType=INTEGER}");
        }
        
        if (record.getIsneedchedk() != null) {
            VALUES("IsNeedChedk", "#{isneedchedk,jdbcType=INTEGER}");
        }
        
        if (record.getSignmode() != null) {
            VALUES("SignMode", "#{signmode,jdbcType=INTEGER}");
        }
        
        if (record.getIsneedconsumptioncontract() != null) {
            VALUES("IsNeedConsumptionContract", "#{isneedconsumptioncontract,jdbcType=INTEGER}");
        }
        
        if (record.getSealpage() != null) {
            VALUES("SealPage", "#{sealpage,jdbcType=INTEGER}");
        }
        
        if (record.getSealpositionx() != null) {
            VALUES("SealPositionX", "#{sealpositionx,jdbcType=INTEGER}");
        }
        
        if (record.getSealpositiony() != null) {
            VALUES("SealPositionY", "#{sealpositiony,jdbcType=INTEGER}");
        }
        
        if (record.getLoanproducttype() != null) {
            VALUES("LoanProductType", "#{loanproducttype,jdbcType=NVARCHAR}");
        }
        
        if (record.getGuaranteeway() != null) {
            VALUES("GuaranteeWay", "#{guaranteeway,jdbcType=NVARCHAR}");
        }
        
        if (record.getInvestmentsorts() != null) {
            VALUES("InvestmentSorts", "#{investmentsorts,jdbcType=NVARCHAR}");
        }
        
        if (record.getBusinesssubdivided() != null) {
            VALUES("BusinessSubdivided", "#{businesssubdivided,jdbcType=NVARCHAR}");
        }
        
        if (record.getContracttempletefileid() != null) {
            VALUES("ContractTempleteFileId", "#{contracttempletefileid,jdbcType=VARCHAR}");
        }
        
        if (record.getGraceperiod() != null) {
            VALUES("GracePeriod", "#{graceperiod,jdbcType=INTEGER}");
        }
        
        if (record.getBuybackperiod() != null) {
            VALUES("BuyBackPeriod", "#{buybackperiod,jdbcType=INTEGER}");
        }
        
        if (record.getContractamountlimit() != null) {
            VALUES("ContractAmountLimit", "#{contractamountlimit,jdbcType=DECIMAL}");
        }
        
        if (record.getIsauthorized() != null) {
            VALUES("IsAuthorized", "#{isauthorized,jdbcType=INTEGER}");
        }
        
        if (record.getDeductchannel() != null) {
            VALUES("DeductChannel", "#{deductchannel,jdbcType=INTEGER}");
        }
        
        if (record.getIsbankcardvalidated() != null) {
            VALUES("IsBankCardValidated", "#{isbankcardvalidated,jdbcType=INTEGER}");
        }
        
        if (record.getIsneedcoborrower() != null) {
            VALUES("IsNeedCoBorrower", "#{isneedcoborrower,jdbcType=INTEGER}");
        }
        
        if (record.getRong360checkfrauds() != null) {
            VALUES("Rong360CheckFrauds", "#{rong360checkfrauds,jdbcType=VARCHAR}");
        }
        
        if (record.getPaymentmode() != null) {
            VALUES("PaymentMode", "#{paymentmode,jdbcType=INTEGER}");
        }
        
        if (record.getTrustbankname() != null) {
            VALUES("TrustBankName", "#{trustbankname,jdbcType=NVARCHAR}");
        }
        
        if (record.getEntrustpersonneedfiles() != null) {
            VALUES("EnTrustPersonNeedFiles", "#{entrustpersonneedfiles,jdbcType=VARCHAR}");
        }
        
        if (record.getEntrustcompanyneedfiles() != null) {
            VALUES("EnTrustCompanyNeedFiles", "#{entrustcompanyneedfiles,jdbcType=VARCHAR}");
        }
        
        if (record.getContractsigninfo() != null) {
            VALUES("ContractSignInfo", "#{contractsigninfo,jdbcType=VARCHAR}");
        }
        
        if (record.getNeedfiletypesformaincontract() != null) {
            VALUES("NeedFileTypesForMainContract", "#{needfiletypesformaincontract,jdbcType=VARCHAR}");
        }
        
        if (record.getNeedfiletypesforsubloancontract() != null) {
            VALUES("NeedFileTypesForSubloanContract", "#{needfiletypesforsubloancontract,jdbcType=VARCHAR}");
        }
        
        if (record.getMaincontractsigntype() != null) {
            VALUES("MainContractSignType", "#{maincontractsigntype,jdbcType=VARCHAR}");
        }
        
        if (record.getSubcontractsigntype() != null) {
            VALUES("SubContractSignType", "#{subcontractsigntype,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Product
     *
     * @mbggenerated Thu Mar 02 13:37:03 CST 2017
     */
    public String selectByExample(CaProductExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("ProductCode");
        } else {
            SELECT("ProductCode");
        }
        SELECT("ProductName");
        SELECT("InvestmentIndustry");
        SELECT("IndustryDetail");
        SELECT("IsCycleLoan");
        SELECT("PenaltyInterestComputing");
        SELECT("LoanInterestComputing");
        SELECT("PenaltyInterest");
        SELECT("PledgeRemind");
        SELECT("InterestRateType");
        SELECT("InterestType");
        SELECT("PartnerCode");
        SELECT("CheckBRFrauds");
        SELECT("DataCreateTime");
        SELECT("DataLastChangeTime");
        SELECT("PaymentAccountNo");
        SELECT("PaymentChannel");
        SELECT("PrefixLoanContractNumber");
        SELECT("IsNeedHandIDCardImage");
        SELECT("IsNeedBankCardImage");
        SELECT("IsNeedEmail");
        SELECT("IsNeedPlatProductName");
        SELECT("IsNeedLoanPurpose");
        SELECT("IsNeedPlatRating");
        SELECT("IsNeedIDCardValidateDate");
        SELECT("IsNeedEmergencyContact");
        SELECT("IsNeedMaritalInfo");
        SELECT("IsNeedPledge");
        SELECT("IsNeedGuarantee");
        SELECT("IsNeedEntrust");
        SELECT("RePayScheduleSource");
        SELECT("IsRePayScheduleRegular");
        SELECT("IsNeedApprove");
        SELECT("AdvanceDaysForAllRepay");
        SELECT("ApplyPaymentSouce");
        SELECT("TrustAccoutNo");
        SELECT("BorrowerAgeBegin");
        SELECT("BorrowerAgeEnd");
        SELECT("IsNeedChedk");
        SELECT("SignMode");
        SELECT("IsNeedConsumptionContract");
        SELECT("SealPage");
        SELECT("SealPositionX");
        SELECT("SealPositionY");
        SELECT("LoanProductType");
        SELECT("GuaranteeWay");
        SELECT("InvestmentSorts");
        SELECT("BusinessSubdivided");
        SELECT("ContractTempleteFileId");
        SELECT("GracePeriod");
        SELECT("BuyBackPeriod");
        SELECT("ContractAmountLimit");
        SELECT("IsAuthorized");
        SELECT("DeductChannel");
        SELECT("IsBankCardValidated");
        SELECT("IsNeedCoBorrower");
        SELECT("Rong360CheckFrauds");
        SELECT("PaymentMode");
        SELECT("TrustBankName");
        SELECT("EnTrustPersonNeedFiles");
        SELECT("EnTrustCompanyNeedFiles");
        SELECT("ContractSignInfo");
        SELECT("NeedFileTypesForMainContract");
        SELECT("NeedFileTypesForSubloanContract");
        SELECT("MainContractSignType");
        SELECT("SubContractSignType");
        FROM("CA_Product");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Product
     *
     * @mbggenerated Thu Mar 02 13:37:03 CST 2017
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        CaProduct record = (CaProduct) parameter.get("record");
        CaProductExample example = (CaProductExample) parameter.get("example");
        
        BEGIN();
        UPDATE("CA_Product");
        
        if (record.getProductcode() != null) {
            SET("ProductCode = #{record.productcode,jdbcType=NVARCHAR}");
        }
        
        if (record.getProductname() != null) {
            SET("ProductName = #{record.productname,jdbcType=NVARCHAR}");
        }
        
        if (record.getInvestmentindustry() != null) {
            SET("InvestmentIndustry = #{record.investmentindustry,jdbcType=NVARCHAR}");
        }
        
        if (record.getIndustrydetail() != null) {
            SET("IndustryDetail = #{record.industrydetail,jdbcType=NVARCHAR}");
        }
        
        if (record.getIscycleloan() != null) {
            SET("IsCycleLoan = #{record.iscycleloan,jdbcType=NVARCHAR}");
        }
        
        if (record.getPenaltyinterestcomputing() != null) {
            SET("PenaltyInterestComputing = #{record.penaltyinterestcomputing,jdbcType=NVARCHAR}");
        }
        
        if (record.getLoaninterestcomputing() != null) {
            SET("LoanInterestComputing = #{record.loaninterestcomputing,jdbcType=NVARCHAR}");
        }
        
        if (record.getPenaltyinterest() != null) {
            SET("PenaltyInterest = #{record.penaltyinterest,jdbcType=DECIMAL}");
        }
        
        if (record.getPledgeremind() != null) {
            SET("PledgeRemind = #{record.pledgeremind,jdbcType=NVARCHAR}");
        }
        
        if (record.getInterestratetype() != null) {
            SET("InterestRateType = #{record.interestratetype,jdbcType=NVARCHAR}");
        }
        
        if (record.getInteresttype() != null) {
            SET("InterestType = #{record.interesttype,jdbcType=NVARCHAR}");
        }
        
        if (record.getPartnercode() != null) {
            SET("PartnerCode = #{record.partnercode,jdbcType=NVARCHAR}");
        }
        
        if (record.getCheckbrfrauds() != null) {
            SET("CheckBRFrauds = #{record.checkbrfrauds,jdbcType=VARCHAR}");
        }
        
        if (record.getDatacreatetime() != null) {
            SET("DataCreateTime = #{record.datacreatetime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getDatalastchangetime() != null) {
            SET("DataLastChangeTime = #{record.datalastchangetime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getPaymentaccountno() != null) {
            SET("PaymentAccountNo = #{record.paymentaccountno,jdbcType=VARCHAR}");
        }
        
        if (record.getPaymentchannel() != null) {
            SET("PaymentChannel = #{record.paymentchannel,jdbcType=INTEGER}");
        }
        
        if (record.getPrefixloancontractnumber() != null) {
            SET("PrefixLoanContractNumber = #{record.prefixloancontractnumber,jdbcType=VARCHAR}");
        }
        
        if (record.getIsneedhandidcardimage() != null) {
            SET("IsNeedHandIDCardImage = #{record.isneedhandidcardimage,jdbcType=INTEGER}");
        }
        
        if (record.getIsneedbankcardimage() != null) {
            SET("IsNeedBankCardImage = #{record.isneedbankcardimage,jdbcType=INTEGER}");
        }
        
        if (record.getIsneedemail() != null) {
            SET("IsNeedEmail = #{record.isneedemail,jdbcType=INTEGER}");
        }
        
        if (record.getIsneedplatproductname() != null) {
            SET("IsNeedPlatProductName = #{record.isneedplatproductname,jdbcType=INTEGER}");
        }
        
        if (record.getIsneedloanpurpose() != null) {
            SET("IsNeedLoanPurpose = #{record.isneedloanpurpose,jdbcType=INTEGER}");
        }
        
        if (record.getIsneedplatrating() != null) {
            SET("IsNeedPlatRating = #{record.isneedplatrating,jdbcType=INTEGER}");
        }
        
        if (record.getIsneedidcardvalidatedate() != null) {
            SET("IsNeedIDCardValidateDate = #{record.isneedidcardvalidatedate,jdbcType=INTEGER}");
        }
        
        if (record.getIsneedemergencycontact() != null) {
            SET("IsNeedEmergencyContact = #{record.isneedemergencycontact,jdbcType=INTEGER}");
        }
        
        if (record.getIsneedmaritalinfo() != null) {
            SET("IsNeedMaritalInfo = #{record.isneedmaritalinfo,jdbcType=INTEGER}");
        }
        
        if (record.getIsneedpledge() != null) {
            SET("IsNeedPledge = #{record.isneedpledge,jdbcType=INTEGER}");
        }
        
        if (record.getIsneedguarantee() != null) {
            SET("IsNeedGuarantee = #{record.isneedguarantee,jdbcType=INTEGER}");
        }
        
        if (record.getIsneedentrust() != null) {
            SET("IsNeedEntrust = #{record.isneedentrust,jdbcType=INTEGER}");
        }
        
        if (record.getRepayschedulesource() != null) {
            SET("RePayScheduleSource = #{record.repayschedulesource,jdbcType=NVARCHAR}");
        }
        
        if (record.getIsrepayscheduleregular() != null) {
            SET("IsRePayScheduleRegular = #{record.isrepayscheduleregular,jdbcType=INTEGER}");
        }
        
        if (record.getIsneedapprove() != null) {
            SET("IsNeedApprove = #{record.isneedapprove,jdbcType=INTEGER}");
        }
        
        if (record.getAdvancedaysforallrepay() != null) {
            SET("AdvanceDaysForAllRepay = #{record.advancedaysforallrepay,jdbcType=INTEGER}");
        }
        
        if (record.getApplypaymentsouce() != null) {
            SET("ApplyPaymentSouce = #{record.applypaymentsouce,jdbcType=INTEGER}");
        }
        
        if (record.getTrustaccoutno() != null) {
            SET("TrustAccoutNo = #{record.trustaccoutno,jdbcType=VARCHAR}");
        }
        
        if (record.getBorroweragebegin() != null) {
            SET("BorrowerAgeBegin = #{record.borroweragebegin,jdbcType=INTEGER}");
        }
        
        if (record.getBorrowerageend() != null) {
            SET("BorrowerAgeEnd = #{record.borrowerageend,jdbcType=INTEGER}");
        }
        
        if (record.getIsneedchedk() != null) {
            SET("IsNeedChedk = #{record.isneedchedk,jdbcType=INTEGER}");
        }
        
        if (record.getSignmode() != null) {
            SET("SignMode = #{record.signmode,jdbcType=INTEGER}");
        }
        
        if (record.getIsneedconsumptioncontract() != null) {
            SET("IsNeedConsumptionContract = #{record.isneedconsumptioncontract,jdbcType=INTEGER}");
        }
        
        if (record.getSealpage() != null) {
            SET("SealPage = #{record.sealpage,jdbcType=INTEGER}");
        }
        
        if (record.getSealpositionx() != null) {
            SET("SealPositionX = #{record.sealpositionx,jdbcType=INTEGER}");
        }
        
        if (record.getSealpositiony() != null) {
            SET("SealPositionY = #{record.sealpositiony,jdbcType=INTEGER}");
        }
        
        if (record.getLoanproducttype() != null) {
            SET("LoanProductType = #{record.loanproducttype,jdbcType=NVARCHAR}");
        }
        
        if (record.getGuaranteeway() != null) {
            SET("GuaranteeWay = #{record.guaranteeway,jdbcType=NVARCHAR}");
        }
        
        if (record.getInvestmentsorts() != null) {
            SET("InvestmentSorts = #{record.investmentsorts,jdbcType=NVARCHAR}");
        }
        
        if (record.getBusinesssubdivided() != null) {
            SET("BusinessSubdivided = #{record.businesssubdivided,jdbcType=NVARCHAR}");
        }
        
        if (record.getContracttempletefileid() != null) {
            SET("ContractTempleteFileId = #{record.contracttempletefileid,jdbcType=VARCHAR}");
        }
        
        if (record.getGraceperiod() != null) {
            SET("GracePeriod = #{record.graceperiod,jdbcType=INTEGER}");
        }
        
        if (record.getBuybackperiod() != null) {
            SET("BuyBackPeriod = #{record.buybackperiod,jdbcType=INTEGER}");
        }
        
        if (record.getContractamountlimit() != null) {
            SET("ContractAmountLimit = #{record.contractamountlimit,jdbcType=DECIMAL}");
        }
        
        if (record.getIsauthorized() != null) {
            SET("IsAuthorized = #{record.isauthorized,jdbcType=INTEGER}");
        }
        
        if (record.getDeductchannel() != null) {
            SET("DeductChannel = #{record.deductchannel,jdbcType=INTEGER}");
        }
        
        if (record.getIsbankcardvalidated() != null) {
            SET("IsBankCardValidated = #{record.isbankcardvalidated,jdbcType=INTEGER}");
        }
        
        if (record.getIsneedcoborrower() != null) {
            SET("IsNeedCoBorrower = #{record.isneedcoborrower,jdbcType=INTEGER}");
        }
        
        if (record.getRong360checkfrauds() != null) {
            SET("Rong360CheckFrauds = #{record.rong360checkfrauds,jdbcType=VARCHAR}");
        }
        
        if (record.getPaymentmode() != null) {
            SET("PaymentMode = #{record.paymentmode,jdbcType=INTEGER}");
        }
        
        if (record.getTrustbankname() != null) {
            SET("TrustBankName = #{record.trustbankname,jdbcType=NVARCHAR}");
        }
        
        if (record.getEntrustpersonneedfiles() != null) {
            SET("EnTrustPersonNeedFiles = #{record.entrustpersonneedfiles,jdbcType=VARCHAR}");
        }
        
        if (record.getEntrustcompanyneedfiles() != null) {
            SET("EnTrustCompanyNeedFiles = #{record.entrustcompanyneedfiles,jdbcType=VARCHAR}");
        }
        
        if (record.getContractsigninfo() != null) {
            SET("ContractSignInfo = #{record.contractsigninfo,jdbcType=VARCHAR}");
        }
        
        if (record.getNeedfiletypesformaincontract() != null) {
            SET("NeedFileTypesForMainContract = #{record.needfiletypesformaincontract,jdbcType=VARCHAR}");
        }
        
        if (record.getNeedfiletypesforsubloancontract() != null) {
            SET("NeedFileTypesForSubloanContract = #{record.needfiletypesforsubloancontract,jdbcType=VARCHAR}");
        }
        
        if (record.getMaincontractsigntype() != null) {
            SET("MainContractSignType = #{record.maincontractsigntype,jdbcType=VARCHAR}");
        }
        
        if (record.getSubcontractsigntype() != null) {
            SET("SubContractSignType = #{record.subcontractsigntype,jdbcType=VARCHAR}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Product
     *
     * @mbggenerated Thu Mar 02 13:37:03 CST 2017
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("CA_Product");
        
        SET("ProductCode = #{record.productcode,jdbcType=NVARCHAR}");
        SET("ProductName = #{record.productname,jdbcType=NVARCHAR}");
        SET("InvestmentIndustry = #{record.investmentindustry,jdbcType=NVARCHAR}");
        SET("IndustryDetail = #{record.industrydetail,jdbcType=NVARCHAR}");
        SET("IsCycleLoan = #{record.iscycleloan,jdbcType=NVARCHAR}");
        SET("PenaltyInterestComputing = #{record.penaltyinterestcomputing,jdbcType=NVARCHAR}");
        SET("LoanInterestComputing = #{record.loaninterestcomputing,jdbcType=NVARCHAR}");
        SET("PenaltyInterest = #{record.penaltyinterest,jdbcType=DECIMAL}");
        SET("PledgeRemind = #{record.pledgeremind,jdbcType=NVARCHAR}");
        SET("InterestRateType = #{record.interestratetype,jdbcType=NVARCHAR}");
        SET("InterestType = #{record.interesttype,jdbcType=NVARCHAR}");
        SET("PartnerCode = #{record.partnercode,jdbcType=NVARCHAR}");
        SET("CheckBRFrauds = #{record.checkbrfrauds,jdbcType=VARCHAR}");
        SET("DataCreateTime = #{record.datacreatetime,jdbcType=TIMESTAMP}");
        SET("DataLastChangeTime = #{record.datalastchangetime,jdbcType=TIMESTAMP}");
        SET("PaymentAccountNo = #{record.paymentaccountno,jdbcType=VARCHAR}");
        SET("PaymentChannel = #{record.paymentchannel,jdbcType=INTEGER}");
        SET("PrefixLoanContractNumber = #{record.prefixloancontractnumber,jdbcType=VARCHAR}");
        SET("IsNeedHandIDCardImage = #{record.isneedhandidcardimage,jdbcType=INTEGER}");
        SET("IsNeedBankCardImage = #{record.isneedbankcardimage,jdbcType=INTEGER}");
        SET("IsNeedEmail = #{record.isneedemail,jdbcType=INTEGER}");
        SET("IsNeedPlatProductName = #{record.isneedplatproductname,jdbcType=INTEGER}");
        SET("IsNeedLoanPurpose = #{record.isneedloanpurpose,jdbcType=INTEGER}");
        SET("IsNeedPlatRating = #{record.isneedplatrating,jdbcType=INTEGER}");
        SET("IsNeedIDCardValidateDate = #{record.isneedidcardvalidatedate,jdbcType=INTEGER}");
        SET("IsNeedEmergencyContact = #{record.isneedemergencycontact,jdbcType=INTEGER}");
        SET("IsNeedMaritalInfo = #{record.isneedmaritalinfo,jdbcType=INTEGER}");
        SET("IsNeedPledge = #{record.isneedpledge,jdbcType=INTEGER}");
        SET("IsNeedGuarantee = #{record.isneedguarantee,jdbcType=INTEGER}");
        SET("IsNeedEntrust = #{record.isneedentrust,jdbcType=INTEGER}");
        SET("RePayScheduleSource = #{record.repayschedulesource,jdbcType=NVARCHAR}");
        SET("IsRePayScheduleRegular = #{record.isrepayscheduleregular,jdbcType=INTEGER}");
        SET("IsNeedApprove = #{record.isneedapprove,jdbcType=INTEGER}");
        SET("AdvanceDaysForAllRepay = #{record.advancedaysforallrepay,jdbcType=INTEGER}");
        SET("ApplyPaymentSouce = #{record.applypaymentsouce,jdbcType=INTEGER}");
        SET("TrustAccoutNo = #{record.trustaccoutno,jdbcType=VARCHAR}");
        SET("BorrowerAgeBegin = #{record.borroweragebegin,jdbcType=INTEGER}");
        SET("BorrowerAgeEnd = #{record.borrowerageend,jdbcType=INTEGER}");
        SET("IsNeedChedk = #{record.isneedchedk,jdbcType=INTEGER}");
        SET("SignMode = #{record.signmode,jdbcType=INTEGER}");
        SET("IsNeedConsumptionContract = #{record.isneedconsumptioncontract,jdbcType=INTEGER}");
        SET("SealPage = #{record.sealpage,jdbcType=INTEGER}");
        SET("SealPositionX = #{record.sealpositionx,jdbcType=INTEGER}");
        SET("SealPositionY = #{record.sealpositiony,jdbcType=INTEGER}");
        SET("LoanProductType = #{record.loanproducttype,jdbcType=NVARCHAR}");
        SET("GuaranteeWay = #{record.guaranteeway,jdbcType=NVARCHAR}");
        SET("InvestmentSorts = #{record.investmentsorts,jdbcType=NVARCHAR}");
        SET("BusinessSubdivided = #{record.businesssubdivided,jdbcType=NVARCHAR}");
        SET("ContractTempleteFileId = #{record.contracttempletefileid,jdbcType=VARCHAR}");
        SET("GracePeriod = #{record.graceperiod,jdbcType=INTEGER}");
        SET("BuyBackPeriod = #{record.buybackperiod,jdbcType=INTEGER}");
        SET("ContractAmountLimit = #{record.contractamountlimit,jdbcType=DECIMAL}");
        SET("IsAuthorized = #{record.isauthorized,jdbcType=INTEGER}");
        SET("DeductChannel = #{record.deductchannel,jdbcType=INTEGER}");
        SET("IsBankCardValidated = #{record.isbankcardvalidated,jdbcType=INTEGER}");
        SET("IsNeedCoBorrower = #{record.isneedcoborrower,jdbcType=INTEGER}");
        SET("Rong360CheckFrauds = #{record.rong360checkfrauds,jdbcType=VARCHAR}");
        SET("PaymentMode = #{record.paymentmode,jdbcType=INTEGER}");
        SET("TrustBankName = #{record.trustbankname,jdbcType=NVARCHAR}");
        SET("EnTrustPersonNeedFiles = #{record.entrustpersonneedfiles,jdbcType=VARCHAR}");
        SET("EnTrustCompanyNeedFiles = #{record.entrustcompanyneedfiles,jdbcType=VARCHAR}");
        SET("ContractSignInfo = #{record.contractsigninfo,jdbcType=VARCHAR}");
        SET("NeedFileTypesForMainContract = #{record.needfiletypesformaincontract,jdbcType=VARCHAR}");
        SET("NeedFileTypesForSubloanContract = #{record.needfiletypesforsubloancontract,jdbcType=VARCHAR}");
        SET("MainContractSignType = #{record.maincontractsigntype,jdbcType=VARCHAR}");
        SET("SubContractSignType = #{record.subcontractsigntype,jdbcType=VARCHAR}");
        
        CaProductExample example = (CaProductExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Product
     *
     * @mbggenerated Thu Mar 02 13:37:03 CST 2017
     */
    public String updateByPrimaryKeySelective(CaProduct record) {
        BEGIN();
        UPDATE("CA_Product");
        
        if (record.getProductname() != null) {
            SET("ProductName = #{productname,jdbcType=NVARCHAR}");
        }
        
        if (record.getInvestmentindustry() != null) {
            SET("InvestmentIndustry = #{investmentindustry,jdbcType=NVARCHAR}");
        }
        
        if (record.getIndustrydetail() != null) {
            SET("IndustryDetail = #{industrydetail,jdbcType=NVARCHAR}");
        }
        
        if (record.getIscycleloan() != null) {
            SET("IsCycleLoan = #{iscycleloan,jdbcType=NVARCHAR}");
        }
        
        if (record.getPenaltyinterestcomputing() != null) {
            SET("PenaltyInterestComputing = #{penaltyinterestcomputing,jdbcType=NVARCHAR}");
        }
        
        if (record.getLoaninterestcomputing() != null) {
            SET("LoanInterestComputing = #{loaninterestcomputing,jdbcType=NVARCHAR}");
        }
        
        if (record.getPenaltyinterest() != null) {
            SET("PenaltyInterest = #{penaltyinterest,jdbcType=DECIMAL}");
        }
        
        if (record.getPledgeremind() != null) {
            SET("PledgeRemind = #{pledgeremind,jdbcType=NVARCHAR}");
        }
        
        if (record.getInterestratetype() != null) {
            SET("InterestRateType = #{interestratetype,jdbcType=NVARCHAR}");
        }
        
        if (record.getInteresttype() != null) {
            SET("InterestType = #{interesttype,jdbcType=NVARCHAR}");
        }
        
        if (record.getPartnercode() != null) {
            SET("PartnerCode = #{partnercode,jdbcType=NVARCHAR}");
        }
        
        if (record.getCheckbrfrauds() != null) {
            SET("CheckBRFrauds = #{checkbrfrauds,jdbcType=VARCHAR}");
        }
        
        if (record.getDatacreatetime() != null) {
            SET("DataCreateTime = #{datacreatetime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getDatalastchangetime() != null) {
            SET("DataLastChangeTime = #{datalastchangetime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getPaymentaccountno() != null) {
            SET("PaymentAccountNo = #{paymentaccountno,jdbcType=VARCHAR}");
        }
        
        if (record.getPaymentchannel() != null) {
            SET("PaymentChannel = #{paymentchannel,jdbcType=INTEGER}");
        }
        
        if (record.getPrefixloancontractnumber() != null) {
            SET("PrefixLoanContractNumber = #{prefixloancontractnumber,jdbcType=VARCHAR}");
        }
        
        if (record.getIsneedhandidcardimage() != null) {
            SET("IsNeedHandIDCardImage = #{isneedhandidcardimage,jdbcType=INTEGER}");
        }
        
        if (record.getIsneedbankcardimage() != null) {
            SET("IsNeedBankCardImage = #{isneedbankcardimage,jdbcType=INTEGER}");
        }
        
        if (record.getIsneedemail() != null) {
            SET("IsNeedEmail = #{isneedemail,jdbcType=INTEGER}");
        }
        
        if (record.getIsneedplatproductname() != null) {
            SET("IsNeedPlatProductName = #{isneedplatproductname,jdbcType=INTEGER}");
        }
        
        if (record.getIsneedloanpurpose() != null) {
            SET("IsNeedLoanPurpose = #{isneedloanpurpose,jdbcType=INTEGER}");
        }
        
        if (record.getIsneedplatrating() != null) {
            SET("IsNeedPlatRating = #{isneedplatrating,jdbcType=INTEGER}");
        }
        
        if (record.getIsneedidcardvalidatedate() != null) {
            SET("IsNeedIDCardValidateDate = #{isneedidcardvalidatedate,jdbcType=INTEGER}");
        }
        
        if (record.getIsneedemergencycontact() != null) {
            SET("IsNeedEmergencyContact = #{isneedemergencycontact,jdbcType=INTEGER}");
        }
        
        if (record.getIsneedmaritalinfo() != null) {
            SET("IsNeedMaritalInfo = #{isneedmaritalinfo,jdbcType=INTEGER}");
        }
        
        if (record.getIsneedpledge() != null) {
            SET("IsNeedPledge = #{isneedpledge,jdbcType=INTEGER}");
        }
        
        if (record.getIsneedguarantee() != null) {
            SET("IsNeedGuarantee = #{isneedguarantee,jdbcType=INTEGER}");
        }
        
        if (record.getIsneedentrust() != null) {
            SET("IsNeedEntrust = #{isneedentrust,jdbcType=INTEGER}");
        }
        
        if (record.getRepayschedulesource() != null) {
            SET("RePayScheduleSource = #{repayschedulesource,jdbcType=NVARCHAR}");
        }
        
        if (record.getIsrepayscheduleregular() != null) {
            SET("IsRePayScheduleRegular = #{isrepayscheduleregular,jdbcType=INTEGER}");
        }
        
        if (record.getIsneedapprove() != null) {
            SET("IsNeedApprove = #{isneedapprove,jdbcType=INTEGER}");
        }
        
        if (record.getAdvancedaysforallrepay() != null) {
            SET("AdvanceDaysForAllRepay = #{advancedaysforallrepay,jdbcType=INTEGER}");
        }
        
        if (record.getApplypaymentsouce() != null) {
            SET("ApplyPaymentSouce = #{applypaymentsouce,jdbcType=INTEGER}");
        }
        
        if (record.getTrustaccoutno() != null) {
            SET("TrustAccoutNo = #{trustaccoutno,jdbcType=VARCHAR}");
        }
        
        if (record.getBorroweragebegin() != null) {
            SET("BorrowerAgeBegin = #{borroweragebegin,jdbcType=INTEGER}");
        }
        
        if (record.getBorrowerageend() != null) {
            SET("BorrowerAgeEnd = #{borrowerageend,jdbcType=INTEGER}");
        }
        
        if (record.getIsneedchedk() != null) {
            SET("IsNeedChedk = #{isneedchedk,jdbcType=INTEGER}");
        }
        
        if (record.getSignmode() != null) {
            SET("SignMode = #{signmode,jdbcType=INTEGER}");
        }
        
        if (record.getIsneedconsumptioncontract() != null) {
            SET("IsNeedConsumptionContract = #{isneedconsumptioncontract,jdbcType=INTEGER}");
        }
        
        if (record.getSealpage() != null) {
            SET("SealPage = #{sealpage,jdbcType=INTEGER}");
        }
        
        if (record.getSealpositionx() != null) {
            SET("SealPositionX = #{sealpositionx,jdbcType=INTEGER}");
        }
        
        if (record.getSealpositiony() != null) {
            SET("SealPositionY = #{sealpositiony,jdbcType=INTEGER}");
        }
        
        if (record.getLoanproducttype() != null) {
            SET("LoanProductType = #{loanproducttype,jdbcType=NVARCHAR}");
        }
        
        if (record.getGuaranteeway() != null) {
            SET("GuaranteeWay = #{guaranteeway,jdbcType=NVARCHAR}");
        }
        
        if (record.getInvestmentsorts() != null) {
            SET("InvestmentSorts = #{investmentsorts,jdbcType=NVARCHAR}");
        }
        
        if (record.getBusinesssubdivided() != null) {
            SET("BusinessSubdivided = #{businesssubdivided,jdbcType=NVARCHAR}");
        }
        
        if (record.getContracttempletefileid() != null) {
            SET("ContractTempleteFileId = #{contracttempletefileid,jdbcType=VARCHAR}");
        }
        
        if (record.getGraceperiod() != null) {
            SET("GracePeriod = #{graceperiod,jdbcType=INTEGER}");
        }
        
        if (record.getBuybackperiod() != null) {
            SET("BuyBackPeriod = #{buybackperiod,jdbcType=INTEGER}");
        }
        
        if (record.getContractamountlimit() != null) {
            SET("ContractAmountLimit = #{contractamountlimit,jdbcType=DECIMAL}");
        }
        
        if (record.getIsauthorized() != null) {
            SET("IsAuthorized = #{isauthorized,jdbcType=INTEGER}");
        }
        
        if (record.getDeductchannel() != null) {
            SET("DeductChannel = #{deductchannel,jdbcType=INTEGER}");
        }
        
        if (record.getIsbankcardvalidated() != null) {
            SET("IsBankCardValidated = #{isbankcardvalidated,jdbcType=INTEGER}");
        }
        
        if (record.getIsneedcoborrower() != null) {
            SET("IsNeedCoBorrower = #{isneedcoborrower,jdbcType=INTEGER}");
        }
        
        if (record.getRong360checkfrauds() != null) {
            SET("Rong360CheckFrauds = #{rong360checkfrauds,jdbcType=VARCHAR}");
        }
        
        if (record.getPaymentmode() != null) {
            SET("PaymentMode = #{paymentmode,jdbcType=INTEGER}");
        }
        
        if (record.getTrustbankname() != null) {
            SET("TrustBankName = #{trustbankname,jdbcType=NVARCHAR}");
        }
        
        if (record.getEntrustpersonneedfiles() != null) {
            SET("EnTrustPersonNeedFiles = #{entrustpersonneedfiles,jdbcType=VARCHAR}");
        }
        
        if (record.getEntrustcompanyneedfiles() != null) {
            SET("EnTrustCompanyNeedFiles = #{entrustcompanyneedfiles,jdbcType=VARCHAR}");
        }
        
        if (record.getContractsigninfo() != null) {
            SET("ContractSignInfo = #{contractsigninfo,jdbcType=VARCHAR}");
        }
        
        if (record.getNeedfiletypesformaincontract() != null) {
            SET("NeedFileTypesForMainContract = #{needfiletypesformaincontract,jdbcType=VARCHAR}");
        }
        
        if (record.getNeedfiletypesforsubloancontract() != null) {
            SET("NeedFileTypesForSubloanContract = #{needfiletypesforsubloancontract,jdbcType=VARCHAR}");
        }
        
        if (record.getMaincontractsigntype() != null) {
            SET("MainContractSignType = #{maincontractsigntype,jdbcType=VARCHAR}");
        }
        
        if (record.getSubcontractsigntype() != null) {
            SET("SubContractSignType = #{subcontractsigntype,jdbcType=VARCHAR}");
        }
        
        WHERE("ProductCode = #{productcode,jdbcType=NVARCHAR}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Product
     *
     * @mbggenerated Thu Mar 02 13:37:03 CST 2017
     */
    protected void applyWhere(CaProductExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}