package com.yunxin.mapper;

import com.yunxin.entity.CaRegion;
import com.yunxin.entity.CaRegionExample;
import com.yunxin.entity.CaRegionExample.Criteria;
import com.yunxin.entity.CaRegionExample.Criterion;

import java.util.List;
import java.util.Map;

import static org.apache.ibatis.jdbc.SqlBuilder.*;

public class CaRegionSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Region
     *
     * @mbggenerated Thu Mar 02 13:37:03 CST 2017
     */
    public String countByExample(CaRegionExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("CA_Region");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Region
     *
     * @mbggenerated Thu Mar 02 13:37:03 CST 2017
     */
    public String deleteByExample(CaRegionExample example) {
        BEGIN();
        DELETE_FROM("CA_Region");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Region
     *
     * @mbggenerated Thu Mar 02 13:37:03 CST 2017
     */
    public String insertSelective(CaRegion record) {
        BEGIN();
        INSERT_INTO("CA_Region");
        
        if (record.getRegioncode() != null) {
            VALUES("RegionCode", "#{regioncode,jdbcType=VARCHAR}");
        }
        
        if (record.getRegionname() != null) {
            VALUES("RegionName", "#{regionname,jdbcType=NVARCHAR}");
        }
        
        if (record.getParentregioncode() != null) {
            VALUES("ParentRegionCode", "#{parentregioncode,jdbcType=VARCHAR}");
        }
        
        if (record.getGrade() != null) {
            VALUES("Grade", "#{grade,jdbcType=INTEGER}");
        }
        
        if (record.getDatacreatetime() != null) {
            VALUES("DataCreateTime", "#{datacreatetime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getDatalastchangetime() != null) {
            VALUES("DataLastChangeTime", "#{datalastchangetime,jdbcType=TIMESTAMP}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Region
     *
     * @mbggenerated Thu Mar 02 13:37:03 CST 2017
     */
    public String selectByExample(CaRegionExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("RegionCode");
        } else {
            SELECT("RegionCode");
        }
        SELECT("RegionName");
        SELECT("ParentRegionCode");
        SELECT("Grade");
        SELECT("DataCreateTime");
        SELECT("DataLastChangeTime");
        FROM("CA_Region");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Region
     *
     * @mbggenerated Thu Mar 02 13:37:03 CST 2017
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        CaRegion record = (CaRegion) parameter.get("record");
        CaRegionExample example = (CaRegionExample) parameter.get("example");
        
        BEGIN();
        UPDATE("CA_Region");
        
        if (record.getRegioncode() != null) {
            SET("RegionCode = #{record.regioncode,jdbcType=VARCHAR}");
        }
        
        if (record.getRegionname() != null) {
            SET("RegionName = #{record.regionname,jdbcType=NVARCHAR}");
        }
        
        if (record.getParentregioncode() != null) {
            SET("ParentRegionCode = #{record.parentregioncode,jdbcType=VARCHAR}");
        }
        
        if (record.getGrade() != null) {
            SET("Grade = #{record.grade,jdbcType=INTEGER}");
        }
        
        if (record.getDatacreatetime() != null) {
            SET("DataCreateTime = #{record.datacreatetime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getDatalastchangetime() != null) {
            SET("DataLastChangeTime = #{record.datalastchangetime,jdbcType=TIMESTAMP}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Region
     *
     * @mbggenerated Thu Mar 02 13:37:03 CST 2017
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("CA_Region");
        
        SET("RegionCode = #{record.regioncode,jdbcType=VARCHAR}");
        SET("RegionName = #{record.regionname,jdbcType=NVARCHAR}");
        SET("ParentRegionCode = #{record.parentregioncode,jdbcType=VARCHAR}");
        SET("Grade = #{record.grade,jdbcType=INTEGER}");
        SET("DataCreateTime = #{record.datacreatetime,jdbcType=TIMESTAMP}");
        SET("DataLastChangeTime = #{record.datalastchangetime,jdbcType=TIMESTAMP}");
        
        CaRegionExample example = (CaRegionExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Region
     *
     * @mbggenerated Thu Mar 02 13:37:03 CST 2017
     */
    public String updateByPrimaryKeySelective(CaRegion record) {
        BEGIN();
        UPDATE("CA_Region");
        
        if (record.getRegionname() != null) {
            SET("RegionName = #{regionname,jdbcType=NVARCHAR}");
        }
        
        if (record.getParentregioncode() != null) {
            SET("ParentRegionCode = #{parentregioncode,jdbcType=VARCHAR}");
        }
        
        if (record.getGrade() != null) {
            SET("Grade = #{grade,jdbcType=INTEGER}");
        }
        
        if (record.getDatacreatetime() != null) {
            SET("DataCreateTime = #{datacreatetime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getDatalastchangetime() != null) {
            SET("DataLastChangeTime = #{datalastchangetime,jdbcType=TIMESTAMP}");
        }
        
        WHERE("RegionCode = #{regioncode,jdbcType=VARCHAR}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Region
     *
     * @mbggenerated Thu Mar 02 13:37:03 CST 2017
     */
    protected void applyWhere(CaRegionExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}