package com.yunxin.mapper;

import com.yunxin.entity.CaRegion;
import com.yunxin.entity.CaRegionExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface CaRegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Region
     *
     * @mbggenerated Thu Mar 02 13:37:03 CST 2017
     */
    @SelectProvider(type=CaRegionSqlProvider.class, method="countByExample")
    int countByExample(CaRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Region
     *
     * @mbggenerated Thu Mar 02 13:37:03 CST 2017
     */
    @DeleteProvider(type=CaRegionSqlProvider.class, method="deleteByExample")
    int deleteByExample(CaRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Region
     *
     * @mbggenerated Thu Mar 02 13:37:03 CST 2017
     */
    @Delete({
        "delete from CA_Region",
        "where RegionCode = #{regioncode,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String regioncode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Region
     *
     * @mbggenerated Thu Mar 02 13:37:03 CST 2017
     */
    @Insert({
        "insert into CA_Region (RegionCode, RegionName, ",
        "ParentRegionCode, Grade, ",
        "DataCreateTime, DataLastChangeTime)",
        "values (#{regioncode,jdbcType=VARCHAR}, #{regionname,jdbcType=NVARCHAR}, ",
        "#{parentregioncode,jdbcType=VARCHAR}, #{grade,jdbcType=INTEGER}, ",
        "#{datacreatetime,jdbcType=TIMESTAMP}, #{datalastchangetime,jdbcType=TIMESTAMP})"
    })
    int insert(CaRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Region
     *
     * @mbggenerated Thu Mar 02 13:37:03 CST 2017
     */
    @InsertProvider(type=CaRegionSqlProvider.class, method="insertSelective")
    int insertSelective(CaRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Region
     *
     * @mbggenerated Thu Mar 02 13:37:03 CST 2017
     */
    @SelectProvider(type=CaRegionSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="RegionCode", property="regioncode", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="RegionName", property="regionname", jdbcType=JdbcType.NVARCHAR),
        @Result(column="ParentRegionCode", property="parentregioncode", jdbcType=JdbcType.VARCHAR),
        @Result(column="Grade", property="grade", jdbcType=JdbcType.INTEGER),
        @Result(column="DataCreateTime", property="datacreatetime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="DataLastChangeTime", property="datalastchangetime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<CaRegion> selectByExample(CaRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Region
     *
     * @mbggenerated Thu Mar 02 13:37:03 CST 2017
     */
    @Select({
        "select",
        "RegionCode, RegionName, ParentRegionCode, Grade, DataCreateTime, DataLastChangeTime",
        "from CA_Region",
        "where RegionCode = #{regioncode,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="RegionCode", property="regioncode", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="RegionName", property="regionname", jdbcType=JdbcType.NVARCHAR),
        @Result(column="ParentRegionCode", property="parentregioncode", jdbcType=JdbcType.VARCHAR),
        @Result(column="Grade", property="grade", jdbcType=JdbcType.INTEGER),
        @Result(column="DataCreateTime", property="datacreatetime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="DataLastChangeTime", property="datalastchangetime", jdbcType=JdbcType.TIMESTAMP)
    })
    CaRegion selectByPrimaryKey(String regioncode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Region
     *
     * @mbggenerated Thu Mar 02 13:37:03 CST 2017
     */
    @UpdateProvider(type=CaRegionSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") CaRegion record, @Param("example") CaRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Region
     *
     * @mbggenerated Thu Mar 02 13:37:03 CST 2017
     */
    @UpdateProvider(type=CaRegionSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") CaRegion record, @Param("example") CaRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Region
     *
     * @mbggenerated Thu Mar 02 13:37:03 CST 2017
     */
    @UpdateProvider(type=CaRegionSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(CaRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Region
     *
     * @mbggenerated Thu Mar 02 13:37:03 CST 2017
     */
    @Update({
        "update CA_Region",
        "set RegionName = #{regionname,jdbcType=NVARCHAR},",
          "ParentRegionCode = #{parentregioncode,jdbcType=VARCHAR},",
          "Grade = #{grade,jdbcType=INTEGER},",
          "DataCreateTime = #{datacreatetime,jdbcType=TIMESTAMP},",
          "DataLastChangeTime = #{datalastchangetime,jdbcType=TIMESTAMP}",
        "where RegionCode = #{regioncode,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(CaRegion record);
}