package com.yunxin.entity;

public class CaBank {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Bank.BankCode
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private String bankcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Bank.BankName
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private String bankname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Bank.Priority
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Bank.GZBankCode
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private String gzbankcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Bank.BankCode
     *
     * @return the value of CA_Bank.BankCode
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public String getBankcode() {
        return bankcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Bank.BankCode
     *
     * @param bankcode the value for CA_Bank.BankCode
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setBankcode(String bankcode) {
        this.bankcode = bankcode == null ? null : bankcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Bank.BankName
     *
     * @return the value of CA_Bank.BankName
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public String getBankname() {
        return bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Bank.BankName
     *
     * @param bankname the value for CA_Bank.BankName
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setBankname(String bankname) {
        this.bankname = bankname == null ? null : bankname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Bank.Priority
     *
     * @return the value of CA_Bank.Priority
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Bank.Priority
     *
     * @param priority the value for CA_Bank.Priority
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Bank.GZBankCode
     *
     * @return the value of CA_Bank.GZBankCode
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public String getGzbankcode() {
        return gzbankcode;
    }

    @Override
    public String toString() {
        return "CaBank{" +
                "bankcode='" + bankcode + '\'' +
                ", bankname='" + bankname + '\'' +
                ", priority=" + priority +
                ", gzbankcode='" + gzbankcode + '\'' +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Bank.GZBankCode
     *
     * @param gzbankcode the value for CA_Bank.GZBankCode
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setGzbankcode(String gzbankcode) {
        this.gzbankcode = gzbankcode == null ? null : gzbankcode.trim();
    }
}