package com.yunxin.entity;

import java.util.Date;

public class CaMerchants {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Merchants.MerId
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private String merid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Merchants.MerchantName
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private String merchantname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Merchants.SecretKey
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private String secretkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Merchants.PublicKey
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private String publickey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Merchants.DataCreateTime
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private Date datacreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Merchants.DataLastChangeTime
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private Date datalastchangetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Merchants.ValidatedRequestIPAddress
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private String validatedrequestipaddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Merchants.MerId
     *
     * @return the value of CA_Merchants.MerId
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public String getMerid() {
        return merid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Merchants.MerId
     *
     * @param merid the value for CA_Merchants.MerId
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setMerid(String merid) {
        this.merid = merid == null ? null : merid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Merchants.MerchantName
     *
     * @return the value of CA_Merchants.MerchantName
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public String getMerchantname() {
        return merchantname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Merchants.MerchantName
     *
     * @param merchantname the value for CA_Merchants.MerchantName
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setMerchantname(String merchantname) {
        this.merchantname = merchantname == null ? null : merchantname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Merchants.SecretKey
     *
     * @return the value of CA_Merchants.SecretKey
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public String getSecretkey() {
        return secretkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Merchants.SecretKey
     *
     * @param secretkey the value for CA_Merchants.SecretKey
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setSecretkey(String secretkey) {
        this.secretkey = secretkey == null ? null : secretkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Merchants.PublicKey
     *
     * @return the value of CA_Merchants.PublicKey
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public String getPublickey() {
        return publickey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Merchants.PublicKey
     *
     * @param publickey the value for CA_Merchants.PublicKey
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setPublickey(String publickey) {
        this.publickey = publickey == null ? null : publickey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Merchants.DataCreateTime
     *
     * @return the value of CA_Merchants.DataCreateTime
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public Date getDatacreatetime() {
        return datacreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Merchants.DataCreateTime
     *
     * @param datacreatetime the value for CA_Merchants.DataCreateTime
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setDatacreatetime(Date datacreatetime) {
        this.datacreatetime = datacreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Merchants.DataLastChangeTime
     *
     * @return the value of CA_Merchants.DataLastChangeTime
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public Date getDatalastchangetime() {
        return datalastchangetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Merchants.DataLastChangeTime
     *
     * @param datalastchangetime the value for CA_Merchants.DataLastChangeTime
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setDatalastchangetime(Date datalastchangetime) {
        this.datalastchangetime = datalastchangetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Merchants.ValidatedRequestIPAddress
     *
     * @return the value of CA_Merchants.ValidatedRequestIPAddress
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public String getValidatedrequestipaddress() {
        return validatedrequestipaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Merchants.ValidatedRequestIPAddress
     *
     * @param validatedrequestipaddress the value for CA_Merchants.ValidatedRequestIPAddress
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setValidatedrequestipaddress(String validatedrequestipaddress) {
        this.validatedrequestipaddress = validatedrequestipaddress == null ? null : validatedrequestipaddress.trim();
    }
}