package com.yunxin.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CaMerchantsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CA_Merchants
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CA_Merchants
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CA_Merchants
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Merchants
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public CaMerchantsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Merchants
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Merchants
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Merchants
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Merchants
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Merchants
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Merchants
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Merchants
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Merchants
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Merchants
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Merchants
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CA_Merchants
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMeridIsNull() {
            addCriterion("MerId is null");
            return (Criteria) this;
        }

        public Criteria andMeridIsNotNull() {
            addCriterion("MerId is not null");
            return (Criteria) this;
        }

        public Criteria andMeridEqualTo(String value) {
            addCriterion("MerId =", value, "merid");
            return (Criteria) this;
        }

        public Criteria andMeridNotEqualTo(String value) {
            addCriterion("MerId <>", value, "merid");
            return (Criteria) this;
        }

        public Criteria andMeridGreaterThan(String value) {
            addCriterion("MerId >", value, "merid");
            return (Criteria) this;
        }

        public Criteria andMeridGreaterThanOrEqualTo(String value) {
            addCriterion("MerId >=", value, "merid");
            return (Criteria) this;
        }

        public Criteria andMeridLessThan(String value) {
            addCriterion("MerId <", value, "merid");
            return (Criteria) this;
        }

        public Criteria andMeridLessThanOrEqualTo(String value) {
            addCriterion("MerId <=", value, "merid");
            return (Criteria) this;
        }

        public Criteria andMeridLike(String value) {
            addCriterion("MerId like", value, "merid");
            return (Criteria) this;
        }

        public Criteria andMeridNotLike(String value) {
            addCriterion("MerId not like", value, "merid");
            return (Criteria) this;
        }

        public Criteria andMeridIn(List<String> values) {
            addCriterion("MerId in", values, "merid");
            return (Criteria) this;
        }

        public Criteria andMeridNotIn(List<String> values) {
            addCriterion("MerId not in", values, "merid");
            return (Criteria) this;
        }

        public Criteria andMeridBetween(String value1, String value2) {
            addCriterion("MerId between", value1, value2, "merid");
            return (Criteria) this;
        }

        public Criteria andMeridNotBetween(String value1, String value2) {
            addCriterion("MerId not between", value1, value2, "merid");
            return (Criteria) this;
        }

        public Criteria andMerchantnameIsNull() {
            addCriterion("MerchantName is null");
            return (Criteria) this;
        }

        public Criteria andMerchantnameIsNotNull() {
            addCriterion("MerchantName is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantnameEqualTo(String value) {
            addCriterion("MerchantName =", value, "merchantname");
            return (Criteria) this;
        }

        public Criteria andMerchantnameNotEqualTo(String value) {
            addCriterion("MerchantName <>", value, "merchantname");
            return (Criteria) this;
        }

        public Criteria andMerchantnameGreaterThan(String value) {
            addCriterion("MerchantName >", value, "merchantname");
            return (Criteria) this;
        }

        public Criteria andMerchantnameGreaterThanOrEqualTo(String value) {
            addCriterion("MerchantName >=", value, "merchantname");
            return (Criteria) this;
        }

        public Criteria andMerchantnameLessThan(String value) {
            addCriterion("MerchantName <", value, "merchantname");
            return (Criteria) this;
        }

        public Criteria andMerchantnameLessThanOrEqualTo(String value) {
            addCriterion("MerchantName <=", value, "merchantname");
            return (Criteria) this;
        }

        public Criteria andMerchantnameLike(String value) {
            addCriterion("MerchantName like", value, "merchantname");
            return (Criteria) this;
        }

        public Criteria andMerchantnameNotLike(String value) {
            addCriterion("MerchantName not like", value, "merchantname");
            return (Criteria) this;
        }

        public Criteria andMerchantnameIn(List<String> values) {
            addCriterion("MerchantName in", values, "merchantname");
            return (Criteria) this;
        }

        public Criteria andMerchantnameNotIn(List<String> values) {
            addCriterion("MerchantName not in", values, "merchantname");
            return (Criteria) this;
        }

        public Criteria andMerchantnameBetween(String value1, String value2) {
            addCriterion("MerchantName between", value1, value2, "merchantname");
            return (Criteria) this;
        }

        public Criteria andMerchantnameNotBetween(String value1, String value2) {
            addCriterion("MerchantName not between", value1, value2, "merchantname");
            return (Criteria) this;
        }

        public Criteria andSecretkeyIsNull() {
            addCriterion("SecretKey is null");
            return (Criteria) this;
        }

        public Criteria andSecretkeyIsNotNull() {
            addCriterion("SecretKey is not null");
            return (Criteria) this;
        }

        public Criteria andSecretkeyEqualTo(String value) {
            addCriterion("SecretKey =", value, "secretkey");
            return (Criteria) this;
        }

        public Criteria andSecretkeyNotEqualTo(String value) {
            addCriterion("SecretKey <>", value, "secretkey");
            return (Criteria) this;
        }

        public Criteria andSecretkeyGreaterThan(String value) {
            addCriterion("SecretKey >", value, "secretkey");
            return (Criteria) this;
        }

        public Criteria andSecretkeyGreaterThanOrEqualTo(String value) {
            addCriterion("SecretKey >=", value, "secretkey");
            return (Criteria) this;
        }

        public Criteria andSecretkeyLessThan(String value) {
            addCriterion("SecretKey <", value, "secretkey");
            return (Criteria) this;
        }

        public Criteria andSecretkeyLessThanOrEqualTo(String value) {
            addCriterion("SecretKey <=", value, "secretkey");
            return (Criteria) this;
        }

        public Criteria andSecretkeyLike(String value) {
            addCriterion("SecretKey like", value, "secretkey");
            return (Criteria) this;
        }

        public Criteria andSecretkeyNotLike(String value) {
            addCriterion("SecretKey not like", value, "secretkey");
            return (Criteria) this;
        }

        public Criteria andSecretkeyIn(List<String> values) {
            addCriterion("SecretKey in", values, "secretkey");
            return (Criteria) this;
        }

        public Criteria andSecretkeyNotIn(List<String> values) {
            addCriterion("SecretKey not in", values, "secretkey");
            return (Criteria) this;
        }

        public Criteria andSecretkeyBetween(String value1, String value2) {
            addCriterion("SecretKey between", value1, value2, "secretkey");
            return (Criteria) this;
        }

        public Criteria andSecretkeyNotBetween(String value1, String value2) {
            addCriterion("SecretKey not between", value1, value2, "secretkey");
            return (Criteria) this;
        }

        public Criteria andPublickeyIsNull() {
            addCriterion("PublicKey is null");
            return (Criteria) this;
        }

        public Criteria andPublickeyIsNotNull() {
            addCriterion("PublicKey is not null");
            return (Criteria) this;
        }

        public Criteria andPublickeyEqualTo(String value) {
            addCriterion("PublicKey =", value, "publickey");
            return (Criteria) this;
        }

        public Criteria andPublickeyNotEqualTo(String value) {
            addCriterion("PublicKey <>", value, "publickey");
            return (Criteria) this;
        }

        public Criteria andPublickeyGreaterThan(String value) {
            addCriterion("PublicKey >", value, "publickey");
            return (Criteria) this;
        }

        public Criteria andPublickeyGreaterThanOrEqualTo(String value) {
            addCriterion("PublicKey >=", value, "publickey");
            return (Criteria) this;
        }

        public Criteria andPublickeyLessThan(String value) {
            addCriterion("PublicKey <", value, "publickey");
            return (Criteria) this;
        }

        public Criteria andPublickeyLessThanOrEqualTo(String value) {
            addCriterion("PublicKey <=", value, "publickey");
            return (Criteria) this;
        }

        public Criteria andPublickeyLike(String value) {
            addCriterion("PublicKey like", value, "publickey");
            return (Criteria) this;
        }

        public Criteria andPublickeyNotLike(String value) {
            addCriterion("PublicKey not like", value, "publickey");
            return (Criteria) this;
        }

        public Criteria andPublickeyIn(List<String> values) {
            addCriterion("PublicKey in", values, "publickey");
            return (Criteria) this;
        }

        public Criteria andPublickeyNotIn(List<String> values) {
            addCriterion("PublicKey not in", values, "publickey");
            return (Criteria) this;
        }

        public Criteria andPublickeyBetween(String value1, String value2) {
            addCriterion("PublicKey between", value1, value2, "publickey");
            return (Criteria) this;
        }

        public Criteria andPublickeyNotBetween(String value1, String value2) {
            addCriterion("PublicKey not between", value1, value2, "publickey");
            return (Criteria) this;
        }

        public Criteria andDatacreatetimeIsNull() {
            addCriterion("DataCreateTime is null");
            return (Criteria) this;
        }

        public Criteria andDatacreatetimeIsNotNull() {
            addCriterion("DataCreateTime is not null");
            return (Criteria) this;
        }

        public Criteria andDatacreatetimeEqualTo(Date value) {
            addCriterion("DataCreateTime =", value, "datacreatetime");
            return (Criteria) this;
        }

        public Criteria andDatacreatetimeNotEqualTo(Date value) {
            addCriterion("DataCreateTime <>", value, "datacreatetime");
            return (Criteria) this;
        }

        public Criteria andDatacreatetimeGreaterThan(Date value) {
            addCriterion("DataCreateTime >", value, "datacreatetime");
            return (Criteria) this;
        }

        public Criteria andDatacreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("DataCreateTime >=", value, "datacreatetime");
            return (Criteria) this;
        }

        public Criteria andDatacreatetimeLessThan(Date value) {
            addCriterion("DataCreateTime <", value, "datacreatetime");
            return (Criteria) this;
        }

        public Criteria andDatacreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("DataCreateTime <=", value, "datacreatetime");
            return (Criteria) this;
        }

        public Criteria andDatacreatetimeIn(List<Date> values) {
            addCriterion("DataCreateTime in", values, "datacreatetime");
            return (Criteria) this;
        }

        public Criteria andDatacreatetimeNotIn(List<Date> values) {
            addCriterion("DataCreateTime not in", values, "datacreatetime");
            return (Criteria) this;
        }

        public Criteria andDatacreatetimeBetween(Date value1, Date value2) {
            addCriterion("DataCreateTime between", value1, value2, "datacreatetime");
            return (Criteria) this;
        }

        public Criteria andDatacreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("DataCreateTime not between", value1, value2, "datacreatetime");
            return (Criteria) this;
        }

        public Criteria andDatalastchangetimeIsNull() {
            addCriterion("DataLastChangeTime is null");
            return (Criteria) this;
        }

        public Criteria andDatalastchangetimeIsNotNull() {
            addCriterion("DataLastChangeTime is not null");
            return (Criteria) this;
        }

        public Criteria andDatalastchangetimeEqualTo(Date value) {
            addCriterion("DataLastChangeTime =", value, "datalastchangetime");
            return (Criteria) this;
        }

        public Criteria andDatalastchangetimeNotEqualTo(Date value) {
            addCriterion("DataLastChangeTime <>", value, "datalastchangetime");
            return (Criteria) this;
        }

        public Criteria andDatalastchangetimeGreaterThan(Date value) {
            addCriterion("DataLastChangeTime >", value, "datalastchangetime");
            return (Criteria) this;
        }

        public Criteria andDatalastchangetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("DataLastChangeTime >=", value, "datalastchangetime");
            return (Criteria) this;
        }

        public Criteria andDatalastchangetimeLessThan(Date value) {
            addCriterion("DataLastChangeTime <", value, "datalastchangetime");
            return (Criteria) this;
        }

        public Criteria andDatalastchangetimeLessThanOrEqualTo(Date value) {
            addCriterion("DataLastChangeTime <=", value, "datalastchangetime");
            return (Criteria) this;
        }

        public Criteria andDatalastchangetimeIn(List<Date> values) {
            addCriterion("DataLastChangeTime in", values, "datalastchangetime");
            return (Criteria) this;
        }

        public Criteria andDatalastchangetimeNotIn(List<Date> values) {
            addCriterion("DataLastChangeTime not in", values, "datalastchangetime");
            return (Criteria) this;
        }

        public Criteria andDatalastchangetimeBetween(Date value1, Date value2) {
            addCriterion("DataLastChangeTime between", value1, value2, "datalastchangetime");
            return (Criteria) this;
        }

        public Criteria andDatalastchangetimeNotBetween(Date value1, Date value2) {
            addCriterion("DataLastChangeTime not between", value1, value2, "datalastchangetime");
            return (Criteria) this;
        }

        public Criteria andValidatedrequestipaddressIsNull() {
            addCriterion("ValidatedRequestIPAddress is null");
            return (Criteria) this;
        }

        public Criteria andValidatedrequestipaddressIsNotNull() {
            addCriterion("ValidatedRequestIPAddress is not null");
            return (Criteria) this;
        }

        public Criteria andValidatedrequestipaddressEqualTo(String value) {
            addCriterion("ValidatedRequestIPAddress =", value, "validatedrequestipaddress");
            return (Criteria) this;
        }

        public Criteria andValidatedrequestipaddressNotEqualTo(String value) {
            addCriterion("ValidatedRequestIPAddress <>", value, "validatedrequestipaddress");
            return (Criteria) this;
        }

        public Criteria andValidatedrequestipaddressGreaterThan(String value) {
            addCriterion("ValidatedRequestIPAddress >", value, "validatedrequestipaddress");
            return (Criteria) this;
        }

        public Criteria andValidatedrequestipaddressGreaterThanOrEqualTo(String value) {
            addCriterion("ValidatedRequestIPAddress >=", value, "validatedrequestipaddress");
            return (Criteria) this;
        }

        public Criteria andValidatedrequestipaddressLessThan(String value) {
            addCriterion("ValidatedRequestIPAddress <", value, "validatedrequestipaddress");
            return (Criteria) this;
        }

        public Criteria andValidatedrequestipaddressLessThanOrEqualTo(String value) {
            addCriterion("ValidatedRequestIPAddress <=", value, "validatedrequestipaddress");
            return (Criteria) this;
        }

        public Criteria andValidatedrequestipaddressLike(String value) {
            addCriterion("ValidatedRequestIPAddress like", value, "validatedrequestipaddress");
            return (Criteria) this;
        }

        public Criteria andValidatedrequestipaddressNotLike(String value) {
            addCriterion("ValidatedRequestIPAddress not like", value, "validatedrequestipaddress");
            return (Criteria) this;
        }

        public Criteria andValidatedrequestipaddressIn(List<String> values) {
            addCriterion("ValidatedRequestIPAddress in", values, "validatedrequestipaddress");
            return (Criteria) this;
        }

        public Criteria andValidatedrequestipaddressNotIn(List<String> values) {
            addCriterion("ValidatedRequestIPAddress not in", values, "validatedrequestipaddress");
            return (Criteria) this;
        }

        public Criteria andValidatedrequestipaddressBetween(String value1, String value2) {
            addCriterion("ValidatedRequestIPAddress between", value1, value2, "validatedrequestipaddress");
            return (Criteria) this;
        }

        public Criteria andValidatedrequestipaddressNotBetween(String value1, String value2) {
            addCriterion("ValidatedRequestIPAddress not between", value1, value2, "validatedrequestipaddress");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CA_Merchants
     *
     * @mbggenerated do_not_delete_during_merge Thu Mar 02 14:53:09 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CA_Merchants
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}