package com.yunxin.entity;

import java.math.BigDecimal;
import java.util.Date;

public class CaProduct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.ProductCode
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private String productcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.ProductName
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private String productname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.InvestmentIndustry
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private String investmentindustry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.IndustryDetail
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private String industrydetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.IsCycleLoan
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private String iscycleloan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.PenaltyInterestComputing
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private String penaltyinterestcomputing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.LoanInterestComputing
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private String loaninterestcomputing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.PenaltyInterest
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private BigDecimal penaltyinterest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.PledgeRemind
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private String pledgeremind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.InterestRateType
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private String interestratetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.InterestType
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private String interesttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.PartnerCode
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private String partnercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.CheckBRFrauds
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private String checkbrfrauds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.DataCreateTime
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private Date datacreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.DataLastChangeTime
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private Date datalastchangetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.PaymentAccountNo
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private String paymentaccountno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.PaymentChannel
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private Integer paymentchannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.PrefixLoanContractNumber
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private String prefixloancontractnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.IsNeedHandIDCardImage
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private Integer isneedhandidcardimage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.IsNeedBankCardImage
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private Integer isneedbankcardimage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.IsNeedEmail
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private Integer isneedemail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.IsNeedPlatProductName
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private Integer isneedplatproductname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.IsNeedLoanPurpose
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private Integer isneedloanpurpose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.IsNeedPlatRating
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private Integer isneedplatrating;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.IsNeedIDCardValidateDate
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private Integer isneedidcardvalidatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.IsNeedEmergencyContact
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private Integer isneedemergencycontact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.IsNeedMaritalInfo
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private Integer isneedmaritalinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.IsNeedPledge
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private Integer isneedpledge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.IsNeedGuarantee
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private Integer isneedguarantee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.IsNeedEntrust
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private Integer isneedentrust;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.RePayScheduleSource
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private String repayschedulesource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.IsRePayScheduleRegular
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private Integer isrepayscheduleregular;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.IsNeedApprove
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private Integer isneedapprove;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.AdvanceDaysForAllRepay
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private Integer advancedaysforallrepay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.ApplyPaymentSouce
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private Integer applypaymentsouce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.TrustAccoutNo
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private String trustaccoutno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.BorrowerAgeBegin
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private Integer borroweragebegin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.BorrowerAgeEnd
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private Integer borrowerageend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.IsNeedChedk
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private Integer isneedchedk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.SignMode
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private Integer signmode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.IsNeedConsumptionContract
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private Integer isneedconsumptioncontract;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.SealPage
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private Integer sealpage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.SealPositionX
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private Integer sealpositionx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.SealPositionY
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private Integer sealpositiony;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.LoanProductType
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private String loanproducttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.GuaranteeWay
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private String guaranteeway;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.InvestmentSorts
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private String investmentsorts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.BusinessSubdivided
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private String businesssubdivided;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.ContractTempleteFileId
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private String contracttempletefileid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.GracePeriod
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private Integer graceperiod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.BuyBackPeriod
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private Integer buybackperiod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.ContractAmountLimit
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private BigDecimal contractamountlimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.IsAuthorized
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private Integer isauthorized;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.DeductChannel
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private Integer deductchannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.IsBankCardValidated
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private Integer isbankcardvalidated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.IsNeedCoBorrower
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private Integer isneedcoborrower;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.Rong360CheckFrauds
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private String rong360checkfrauds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.PaymentMode
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private Integer paymentmode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.TrustBankName
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private String trustbankname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.EnTrustPersonNeedFiles
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private String entrustpersonneedfiles;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.EnTrustCompanyNeedFiles
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private String entrustcompanyneedfiles;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.ContractSignInfo
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private String contractsigninfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.NeedFileTypesForMainContract
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private String needfiletypesformaincontract;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.NeedFileTypesForSubloanContract
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private String needfiletypesforsubloancontract;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.MainContractSignType
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private String maincontractsigntype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Product.SubContractSignType
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private String subcontractsigntype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.ProductCode
     *
     * @return the value of CA_Product.ProductCode
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public String getProductcode() {
        return productcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.ProductCode
     *
     * @param productcode the value for CA_Product.ProductCode
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setProductcode(String productcode) {
        this.productcode = productcode == null ? null : productcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.ProductName
     *
     * @return the value of CA_Product.ProductName
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public String getProductname() {
        return productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.ProductName
     *
     * @param productname the value for CA_Product.ProductName
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setProductname(String productname) {
        this.productname = productname == null ? null : productname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.InvestmentIndustry
     *
     * @return the value of CA_Product.InvestmentIndustry
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public String getInvestmentindustry() {
        return investmentindustry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.InvestmentIndustry
     *
     * @param investmentindustry the value for CA_Product.InvestmentIndustry
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setInvestmentindustry(String investmentindustry) {
        this.investmentindustry = investmentindustry == null ? null : investmentindustry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.IndustryDetail
     *
     * @return the value of CA_Product.IndustryDetail
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public String getIndustrydetail() {
        return industrydetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.IndustryDetail
     *
     * @param industrydetail the value for CA_Product.IndustryDetail
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setIndustrydetail(String industrydetail) {
        this.industrydetail = industrydetail == null ? null : industrydetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.IsCycleLoan
     *
     * @return the value of CA_Product.IsCycleLoan
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public String getIscycleloan() {
        return iscycleloan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.IsCycleLoan
     *
     * @param iscycleloan the value for CA_Product.IsCycleLoan
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setIscycleloan(String iscycleloan) {
        this.iscycleloan = iscycleloan == null ? null : iscycleloan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.PenaltyInterestComputing
     *
     * @return the value of CA_Product.PenaltyInterestComputing
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public String getPenaltyinterestcomputing() {
        return penaltyinterestcomputing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.PenaltyInterestComputing
     *
     * @param penaltyinterestcomputing the value for CA_Product.PenaltyInterestComputing
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setPenaltyinterestcomputing(String penaltyinterestcomputing) {
        this.penaltyinterestcomputing = penaltyinterestcomputing == null ? null : penaltyinterestcomputing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.LoanInterestComputing
     *
     * @return the value of CA_Product.LoanInterestComputing
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public String getLoaninterestcomputing() {
        return loaninterestcomputing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.LoanInterestComputing
     *
     * @param loaninterestcomputing the value for CA_Product.LoanInterestComputing
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setLoaninterestcomputing(String loaninterestcomputing) {
        this.loaninterestcomputing = loaninterestcomputing == null ? null : loaninterestcomputing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.PenaltyInterest
     *
     * @return the value of CA_Product.PenaltyInterest
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public BigDecimal getPenaltyinterest() {
        return penaltyinterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.PenaltyInterest
     *
     * @param penaltyinterest the value for CA_Product.PenaltyInterest
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setPenaltyinterest(BigDecimal penaltyinterest) {
        this.penaltyinterest = penaltyinterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.PledgeRemind
     *
     * @return the value of CA_Product.PledgeRemind
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public String getPledgeremind() {
        return pledgeremind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.PledgeRemind
     *
     * @param pledgeremind the value for CA_Product.PledgeRemind
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setPledgeremind(String pledgeremind) {
        this.pledgeremind = pledgeremind == null ? null : pledgeremind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.InterestRateType
     *
     * @return the value of CA_Product.InterestRateType
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public String getInterestratetype() {
        return interestratetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.InterestRateType
     *
     * @param interestratetype the value for CA_Product.InterestRateType
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setInterestratetype(String interestratetype) {
        this.interestratetype = interestratetype == null ? null : interestratetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.InterestType
     *
     * @return the value of CA_Product.InterestType
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public String getInteresttype() {
        return interesttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.InterestType
     *
     * @param interesttype the value for CA_Product.InterestType
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setInteresttype(String interesttype) {
        this.interesttype = interesttype == null ? null : interesttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.PartnerCode
     *
     * @return the value of CA_Product.PartnerCode
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public String getPartnercode() {
        return partnercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.PartnerCode
     *
     * @param partnercode the value for CA_Product.PartnerCode
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setPartnercode(String partnercode) {
        this.partnercode = partnercode == null ? null : partnercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.CheckBRFrauds
     *
     * @return the value of CA_Product.CheckBRFrauds
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public String getCheckbrfrauds() {
        return checkbrfrauds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.CheckBRFrauds
     *
     * @param checkbrfrauds the value for CA_Product.CheckBRFrauds
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setCheckbrfrauds(String checkbrfrauds) {
        this.checkbrfrauds = checkbrfrauds == null ? null : checkbrfrauds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.DataCreateTime
     *
     * @return the value of CA_Product.DataCreateTime
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public Date getDatacreatetime() {
        return datacreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.DataCreateTime
     *
     * @param datacreatetime the value for CA_Product.DataCreateTime
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setDatacreatetime(Date datacreatetime) {
        this.datacreatetime = datacreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.DataLastChangeTime
     *
     * @return the value of CA_Product.DataLastChangeTime
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public Date getDatalastchangetime() {
        return datalastchangetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.DataLastChangeTime
     *
     * @param datalastchangetime the value for CA_Product.DataLastChangeTime
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setDatalastchangetime(Date datalastchangetime) {
        this.datalastchangetime = datalastchangetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.PaymentAccountNo
     *
     * @return the value of CA_Product.PaymentAccountNo
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public String getPaymentaccountno() {
        return paymentaccountno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.PaymentAccountNo
     *
     * @param paymentaccountno the value for CA_Product.PaymentAccountNo
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setPaymentaccountno(String paymentaccountno) {
        this.paymentaccountno = paymentaccountno == null ? null : paymentaccountno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.PaymentChannel
     *
     * @return the value of CA_Product.PaymentChannel
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public Integer getPaymentchannel() {
        return paymentchannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.PaymentChannel
     *
     * @param paymentchannel the value for CA_Product.PaymentChannel
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setPaymentchannel(Integer paymentchannel) {
        this.paymentchannel = paymentchannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.PrefixLoanContractNumber
     *
     * @return the value of CA_Product.PrefixLoanContractNumber
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public String getPrefixloancontractnumber() {
        return prefixloancontractnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.PrefixLoanContractNumber
     *
     * @param prefixloancontractnumber the value for CA_Product.PrefixLoanContractNumber
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setPrefixloancontractnumber(String prefixloancontractnumber) {
        this.prefixloancontractnumber = prefixloancontractnumber == null ? null : prefixloancontractnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.IsNeedHandIDCardImage
     *
     * @return the value of CA_Product.IsNeedHandIDCardImage
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public Integer getIsneedhandidcardimage() {
        return isneedhandidcardimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.IsNeedHandIDCardImage
     *
     * @param isneedhandidcardimage the value for CA_Product.IsNeedHandIDCardImage
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setIsneedhandidcardimage(Integer isneedhandidcardimage) {
        this.isneedhandidcardimage = isneedhandidcardimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.IsNeedBankCardImage
     *
     * @return the value of CA_Product.IsNeedBankCardImage
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public Integer getIsneedbankcardimage() {
        return isneedbankcardimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.IsNeedBankCardImage
     *
     * @param isneedbankcardimage the value for CA_Product.IsNeedBankCardImage
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setIsneedbankcardimage(Integer isneedbankcardimage) {
        this.isneedbankcardimage = isneedbankcardimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.IsNeedEmail
     *
     * @return the value of CA_Product.IsNeedEmail
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public Integer getIsneedemail() {
        return isneedemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.IsNeedEmail
     *
     * @param isneedemail the value for CA_Product.IsNeedEmail
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setIsneedemail(Integer isneedemail) {
        this.isneedemail = isneedemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.IsNeedPlatProductName
     *
     * @return the value of CA_Product.IsNeedPlatProductName
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public Integer getIsneedplatproductname() {
        return isneedplatproductname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.IsNeedPlatProductName
     *
     * @param isneedplatproductname the value for CA_Product.IsNeedPlatProductName
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setIsneedplatproductname(Integer isneedplatproductname) {
        this.isneedplatproductname = isneedplatproductname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.IsNeedLoanPurpose
     *
     * @return the value of CA_Product.IsNeedLoanPurpose
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public Integer getIsneedloanpurpose() {
        return isneedloanpurpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.IsNeedLoanPurpose
     *
     * @param isneedloanpurpose the value for CA_Product.IsNeedLoanPurpose
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setIsneedloanpurpose(Integer isneedloanpurpose) {
        this.isneedloanpurpose = isneedloanpurpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.IsNeedPlatRating
     *
     * @return the value of CA_Product.IsNeedPlatRating
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public Integer getIsneedplatrating() {
        return isneedplatrating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.IsNeedPlatRating
     *
     * @param isneedplatrating the value for CA_Product.IsNeedPlatRating
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setIsneedplatrating(Integer isneedplatrating) {
        this.isneedplatrating = isneedplatrating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.IsNeedIDCardValidateDate
     *
     * @return the value of CA_Product.IsNeedIDCardValidateDate
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public Integer getIsneedidcardvalidatedate() {
        return isneedidcardvalidatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.IsNeedIDCardValidateDate
     *
     * @param isneedidcardvalidatedate the value for CA_Product.IsNeedIDCardValidateDate
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setIsneedidcardvalidatedate(Integer isneedidcardvalidatedate) {
        this.isneedidcardvalidatedate = isneedidcardvalidatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.IsNeedEmergencyContact
     *
     * @return the value of CA_Product.IsNeedEmergencyContact
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public Integer getIsneedemergencycontact() {
        return isneedemergencycontact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.IsNeedEmergencyContact
     *
     * @param isneedemergencycontact the value for CA_Product.IsNeedEmergencyContact
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setIsneedemergencycontact(Integer isneedemergencycontact) {
        this.isneedemergencycontact = isneedemergencycontact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.IsNeedMaritalInfo
     *
     * @return the value of CA_Product.IsNeedMaritalInfo
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public Integer getIsneedmaritalinfo() {
        return isneedmaritalinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.IsNeedMaritalInfo
     *
     * @param isneedmaritalinfo the value for CA_Product.IsNeedMaritalInfo
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setIsneedmaritalinfo(Integer isneedmaritalinfo) {
        this.isneedmaritalinfo = isneedmaritalinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.IsNeedPledge
     *
     * @return the value of CA_Product.IsNeedPledge
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public Integer getIsneedpledge() {
        return isneedpledge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.IsNeedPledge
     *
     * @param isneedpledge the value for CA_Product.IsNeedPledge
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setIsneedpledge(Integer isneedpledge) {
        this.isneedpledge = isneedpledge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.IsNeedGuarantee
     *
     * @return the value of CA_Product.IsNeedGuarantee
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public Integer getIsneedguarantee() {
        return isneedguarantee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.IsNeedGuarantee
     *
     * @param isneedguarantee the value for CA_Product.IsNeedGuarantee
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setIsneedguarantee(Integer isneedguarantee) {
        this.isneedguarantee = isneedguarantee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.IsNeedEntrust
     *
     * @return the value of CA_Product.IsNeedEntrust
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public Integer getIsneedentrust() {
        return isneedentrust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.IsNeedEntrust
     *
     * @param isneedentrust the value for CA_Product.IsNeedEntrust
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setIsneedentrust(Integer isneedentrust) {
        this.isneedentrust = isneedentrust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.RePayScheduleSource
     *
     * @return the value of CA_Product.RePayScheduleSource
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public String getRepayschedulesource() {
        return repayschedulesource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.RePayScheduleSource
     *
     * @param repayschedulesource the value for CA_Product.RePayScheduleSource
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setRepayschedulesource(String repayschedulesource) {
        this.repayschedulesource = repayschedulesource == null ? null : repayschedulesource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.IsRePayScheduleRegular
     *
     * @return the value of CA_Product.IsRePayScheduleRegular
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public Integer getIsrepayscheduleregular() {
        return isrepayscheduleregular;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.IsRePayScheduleRegular
     *
     * @param isrepayscheduleregular the value for CA_Product.IsRePayScheduleRegular
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setIsrepayscheduleregular(Integer isrepayscheduleregular) {
        this.isrepayscheduleregular = isrepayscheduleregular;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.IsNeedApprove
     *
     * @return the value of CA_Product.IsNeedApprove
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public Integer getIsneedapprove() {
        return isneedapprove;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.IsNeedApprove
     *
     * @param isneedapprove the value for CA_Product.IsNeedApprove
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setIsneedapprove(Integer isneedapprove) {
        this.isneedapprove = isneedapprove;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.AdvanceDaysForAllRepay
     *
     * @return the value of CA_Product.AdvanceDaysForAllRepay
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public Integer getAdvancedaysforallrepay() {
        return advancedaysforallrepay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.AdvanceDaysForAllRepay
     *
     * @param advancedaysforallrepay the value for CA_Product.AdvanceDaysForAllRepay
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setAdvancedaysforallrepay(Integer advancedaysforallrepay) {
        this.advancedaysforallrepay = advancedaysforallrepay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.ApplyPaymentSouce
     *
     * @return the value of CA_Product.ApplyPaymentSouce
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public Integer getApplypaymentsouce() {
        return applypaymentsouce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.ApplyPaymentSouce
     *
     * @param applypaymentsouce the value for CA_Product.ApplyPaymentSouce
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setApplypaymentsouce(Integer applypaymentsouce) {
        this.applypaymentsouce = applypaymentsouce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.TrustAccoutNo
     *
     * @return the value of CA_Product.TrustAccoutNo
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public String getTrustaccoutno() {
        return trustaccoutno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.TrustAccoutNo
     *
     * @param trustaccoutno the value for CA_Product.TrustAccoutNo
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setTrustaccoutno(String trustaccoutno) {
        this.trustaccoutno = trustaccoutno == null ? null : trustaccoutno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.BorrowerAgeBegin
     *
     * @return the value of CA_Product.BorrowerAgeBegin
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public Integer getBorroweragebegin() {
        return borroweragebegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.BorrowerAgeBegin
     *
     * @param borroweragebegin the value for CA_Product.BorrowerAgeBegin
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setBorroweragebegin(Integer borroweragebegin) {
        this.borroweragebegin = borroweragebegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.BorrowerAgeEnd
     *
     * @return the value of CA_Product.BorrowerAgeEnd
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public Integer getBorrowerageend() {
        return borrowerageend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.BorrowerAgeEnd
     *
     * @param borrowerageend the value for CA_Product.BorrowerAgeEnd
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setBorrowerageend(Integer borrowerageend) {
        this.borrowerageend = borrowerageend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.IsNeedChedk
     *
     * @return the value of CA_Product.IsNeedChedk
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public Integer getIsneedchedk() {
        return isneedchedk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.IsNeedChedk
     *
     * @param isneedchedk the value for CA_Product.IsNeedChedk
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setIsneedchedk(Integer isneedchedk) {
        this.isneedchedk = isneedchedk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.SignMode
     *
     * @return the value of CA_Product.SignMode
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public Integer getSignmode() {
        return signmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.SignMode
     *
     * @param signmode the value for CA_Product.SignMode
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setSignmode(Integer signmode) {
        this.signmode = signmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.IsNeedConsumptionContract
     *
     * @return the value of CA_Product.IsNeedConsumptionContract
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public Integer getIsneedconsumptioncontract() {
        return isneedconsumptioncontract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.IsNeedConsumptionContract
     *
     * @param isneedconsumptioncontract the value for CA_Product.IsNeedConsumptionContract
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setIsneedconsumptioncontract(Integer isneedconsumptioncontract) {
        this.isneedconsumptioncontract = isneedconsumptioncontract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.SealPage
     *
     * @return the value of CA_Product.SealPage
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public Integer getSealpage() {
        return sealpage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.SealPage
     *
     * @param sealpage the value for CA_Product.SealPage
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setSealpage(Integer sealpage) {
        this.sealpage = sealpage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.SealPositionX
     *
     * @return the value of CA_Product.SealPositionX
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public Integer getSealpositionx() {
        return sealpositionx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.SealPositionX
     *
     * @param sealpositionx the value for CA_Product.SealPositionX
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setSealpositionx(Integer sealpositionx) {
        this.sealpositionx = sealpositionx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.SealPositionY
     *
     * @return the value of CA_Product.SealPositionY
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public Integer getSealpositiony() {
        return sealpositiony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.SealPositionY
     *
     * @param sealpositiony the value for CA_Product.SealPositionY
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setSealpositiony(Integer sealpositiony) {
        this.sealpositiony = sealpositiony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.LoanProductType
     *
     * @return the value of CA_Product.LoanProductType
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public String getLoanproducttype() {
        return loanproducttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.LoanProductType
     *
     * @param loanproducttype the value for CA_Product.LoanProductType
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setLoanproducttype(String loanproducttype) {
        this.loanproducttype = loanproducttype == null ? null : loanproducttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.GuaranteeWay
     *
     * @return the value of CA_Product.GuaranteeWay
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public String getGuaranteeway() {
        return guaranteeway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.GuaranteeWay
     *
     * @param guaranteeway the value for CA_Product.GuaranteeWay
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setGuaranteeway(String guaranteeway) {
        this.guaranteeway = guaranteeway == null ? null : guaranteeway.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.InvestmentSorts
     *
     * @return the value of CA_Product.InvestmentSorts
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public String getInvestmentsorts() {
        return investmentsorts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.InvestmentSorts
     *
     * @param investmentsorts the value for CA_Product.InvestmentSorts
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setInvestmentsorts(String investmentsorts) {
        this.investmentsorts = investmentsorts == null ? null : investmentsorts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.BusinessSubdivided
     *
     * @return the value of CA_Product.BusinessSubdivided
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public String getBusinesssubdivided() {
        return businesssubdivided;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.BusinessSubdivided
     *
     * @param businesssubdivided the value for CA_Product.BusinessSubdivided
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setBusinesssubdivided(String businesssubdivided) {
        this.businesssubdivided = businesssubdivided == null ? null : businesssubdivided.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.ContractTempleteFileId
     *
     * @return the value of CA_Product.ContractTempleteFileId
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public String getContracttempletefileid() {
        return contracttempletefileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.ContractTempleteFileId
     *
     * @param contracttempletefileid the value for CA_Product.ContractTempleteFileId
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setContracttempletefileid(String contracttempletefileid) {
        this.contracttempletefileid = contracttempletefileid == null ? null : contracttempletefileid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.GracePeriod
     *
     * @return the value of CA_Product.GracePeriod
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public Integer getGraceperiod() {
        return graceperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.GracePeriod
     *
     * @param graceperiod the value for CA_Product.GracePeriod
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setGraceperiod(Integer graceperiod) {
        this.graceperiod = graceperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.BuyBackPeriod
     *
     * @return the value of CA_Product.BuyBackPeriod
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public Integer getBuybackperiod() {
        return buybackperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.BuyBackPeriod
     *
     * @param buybackperiod the value for CA_Product.BuyBackPeriod
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setBuybackperiod(Integer buybackperiod) {
        this.buybackperiod = buybackperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.ContractAmountLimit
     *
     * @return the value of CA_Product.ContractAmountLimit
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public BigDecimal getContractamountlimit() {
        return contractamountlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.ContractAmountLimit
     *
     * @param contractamountlimit the value for CA_Product.ContractAmountLimit
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setContractamountlimit(BigDecimal contractamountlimit) {
        this.contractamountlimit = contractamountlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.IsAuthorized
     *
     * @return the value of CA_Product.IsAuthorized
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public Integer getIsauthorized() {
        return isauthorized;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.IsAuthorized
     *
     * @param isauthorized the value for CA_Product.IsAuthorized
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setIsauthorized(Integer isauthorized) {
        this.isauthorized = isauthorized;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.DeductChannel
     *
     * @return the value of CA_Product.DeductChannel
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public Integer getDeductchannel() {
        return deductchannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.DeductChannel
     *
     * @param deductchannel the value for CA_Product.DeductChannel
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setDeductchannel(Integer deductchannel) {
        this.deductchannel = deductchannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.IsBankCardValidated
     *
     * @return the value of CA_Product.IsBankCardValidated
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public Integer getIsbankcardvalidated() {
        return isbankcardvalidated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.IsBankCardValidated
     *
     * @param isbankcardvalidated the value for CA_Product.IsBankCardValidated
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setIsbankcardvalidated(Integer isbankcardvalidated) {
        this.isbankcardvalidated = isbankcardvalidated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.IsNeedCoBorrower
     *
     * @return the value of CA_Product.IsNeedCoBorrower
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public Integer getIsneedcoborrower() {
        return isneedcoborrower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.IsNeedCoBorrower
     *
     * @param isneedcoborrower the value for CA_Product.IsNeedCoBorrower
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setIsneedcoborrower(Integer isneedcoborrower) {
        this.isneedcoborrower = isneedcoborrower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.Rong360CheckFrauds
     *
     * @return the value of CA_Product.Rong360CheckFrauds
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public String getRong360checkfrauds() {
        return rong360checkfrauds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.Rong360CheckFrauds
     *
     * @param rong360checkfrauds the value for CA_Product.Rong360CheckFrauds
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setRong360checkfrauds(String rong360checkfrauds) {
        this.rong360checkfrauds = rong360checkfrauds == null ? null : rong360checkfrauds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.PaymentMode
     *
     * @return the value of CA_Product.PaymentMode
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public Integer getPaymentmode() {
        return paymentmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.PaymentMode
     *
     * @param paymentmode the value for CA_Product.PaymentMode
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setPaymentmode(Integer paymentmode) {
        this.paymentmode = paymentmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.TrustBankName
     *
     * @return the value of CA_Product.TrustBankName
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public String getTrustbankname() {
        return trustbankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.TrustBankName
     *
     * @param trustbankname the value for CA_Product.TrustBankName
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setTrustbankname(String trustbankname) {
        this.trustbankname = trustbankname == null ? null : trustbankname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.EnTrustPersonNeedFiles
     *
     * @return the value of CA_Product.EnTrustPersonNeedFiles
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public String getEntrustpersonneedfiles() {
        return entrustpersonneedfiles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.EnTrustPersonNeedFiles
     *
     * @param entrustpersonneedfiles the value for CA_Product.EnTrustPersonNeedFiles
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setEntrustpersonneedfiles(String entrustpersonneedfiles) {
        this.entrustpersonneedfiles = entrustpersonneedfiles == null ? null : entrustpersonneedfiles.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.EnTrustCompanyNeedFiles
     *
     * @return the value of CA_Product.EnTrustCompanyNeedFiles
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public String getEntrustcompanyneedfiles() {
        return entrustcompanyneedfiles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.EnTrustCompanyNeedFiles
     *
     * @param entrustcompanyneedfiles the value for CA_Product.EnTrustCompanyNeedFiles
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setEntrustcompanyneedfiles(String entrustcompanyneedfiles) {
        this.entrustcompanyneedfiles = entrustcompanyneedfiles == null ? null : entrustcompanyneedfiles.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.ContractSignInfo
     *
     * @return the value of CA_Product.ContractSignInfo
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public String getContractsigninfo() {
        return contractsigninfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.ContractSignInfo
     *
     * @param contractsigninfo the value for CA_Product.ContractSignInfo
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setContractsigninfo(String contractsigninfo) {
        this.contractsigninfo = contractsigninfo == null ? null : contractsigninfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.NeedFileTypesForMainContract
     *
     * @return the value of CA_Product.NeedFileTypesForMainContract
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public String getNeedfiletypesformaincontract() {
        return needfiletypesformaincontract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.NeedFileTypesForMainContract
     *
     * @param needfiletypesformaincontract the value for CA_Product.NeedFileTypesForMainContract
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setNeedfiletypesformaincontract(String needfiletypesformaincontract) {
        this.needfiletypesformaincontract = needfiletypesformaincontract == null ? null : needfiletypesformaincontract.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.NeedFileTypesForSubloanContract
     *
     * @return the value of CA_Product.NeedFileTypesForSubloanContract
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public String getNeedfiletypesforsubloancontract() {
        return needfiletypesforsubloancontract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.NeedFileTypesForSubloanContract
     *
     * @param needfiletypesforsubloancontract the value for CA_Product.NeedFileTypesForSubloanContract
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setNeedfiletypesforsubloancontract(String needfiletypesforsubloancontract) {
        this.needfiletypesforsubloancontract = needfiletypesforsubloancontract == null ? null : needfiletypesforsubloancontract.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.MainContractSignType
     *
     * @return the value of CA_Product.MainContractSignType
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public String getMaincontractsigntype() {
        return maincontractsigntype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.MainContractSignType
     *
     * @param maincontractsigntype the value for CA_Product.MainContractSignType
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setMaincontractsigntype(String maincontractsigntype) {
        this.maincontractsigntype = maincontractsigntype == null ? null : maincontractsigntype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Product.SubContractSignType
     *
     * @return the value of CA_Product.SubContractSignType
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public String getSubcontractsigntype() {
        return subcontractsigntype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Product.SubContractSignType
     *
     * @param subcontractsigntype the value for CA_Product.SubContractSignType
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setSubcontractsigntype(String subcontractsigntype) {
        this.subcontractsigntype = subcontractsigntype == null ? null : subcontractsigntype.trim();
    }
}