package com.yunxin.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CaRegionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CA_Region
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CA_Region
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CA_Region
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Region
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public CaRegionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Region
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Region
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Region
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Region
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Region
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Region
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Region
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Region
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Region
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CA_Region
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CA_Region
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRegioncodeIsNull() {
            addCriterion("RegionCode is null");
            return (Criteria) this;
        }

        public Criteria andRegioncodeIsNotNull() {
            addCriterion("RegionCode is not null");
            return (Criteria) this;
        }

        public Criteria andRegioncodeEqualTo(String value) {
            addCriterion("RegionCode =", value, "regioncode");
            return (Criteria) this;
        }

        public Criteria andRegioncodeNotEqualTo(String value) {
            addCriterion("RegionCode <>", value, "regioncode");
            return (Criteria) this;
        }

        public Criteria andRegioncodeGreaterThan(String value) {
            addCriterion("RegionCode >", value, "regioncode");
            return (Criteria) this;
        }

        public Criteria andRegioncodeGreaterThanOrEqualTo(String value) {
            addCriterion("RegionCode >=", value, "regioncode");
            return (Criteria) this;
        }

        public Criteria andRegioncodeLessThan(String value) {
            addCriterion("RegionCode <", value, "regioncode");
            return (Criteria) this;
        }

        public Criteria andRegioncodeLessThanOrEqualTo(String value) {
            addCriterion("RegionCode <=", value, "regioncode");
            return (Criteria) this;
        }

        public Criteria andRegioncodeLike(String value) {
            addCriterion("RegionCode like", value, "regioncode");
            return (Criteria) this;
        }

        public Criteria andRegioncodeNotLike(String value) {
            addCriterion("RegionCode not like", value, "regioncode");
            return (Criteria) this;
        }

        public Criteria andRegioncodeIn(List<String> values) {
            addCriterion("RegionCode in", values, "regioncode");
            return (Criteria) this;
        }

        public Criteria andRegioncodeNotIn(List<String> values) {
            addCriterion("RegionCode not in", values, "regioncode");
            return (Criteria) this;
        }

        public Criteria andRegioncodeBetween(String value1, String value2) {
            addCriterion("RegionCode between", value1, value2, "regioncode");
            return (Criteria) this;
        }

        public Criteria andRegioncodeNotBetween(String value1, String value2) {
            addCriterion("RegionCode not between", value1, value2, "regioncode");
            return (Criteria) this;
        }

        public Criteria andRegionnameIsNull() {
            addCriterion("RegionName is null");
            return (Criteria) this;
        }

        public Criteria andRegionnameIsNotNull() {
            addCriterion("RegionName is not null");
            return (Criteria) this;
        }

        public Criteria andRegionnameEqualTo(String value) {
            addCriterion("RegionName =", value, "regionname");
            return (Criteria) this;
        }

        public Criteria andRegionnameNotEqualTo(String value) {
            addCriterion("RegionName <>", value, "regionname");
            return (Criteria) this;
        }

        public Criteria andRegionnameGreaterThan(String value) {
            addCriterion("RegionName >", value, "regionname");
            return (Criteria) this;
        }

        public Criteria andRegionnameGreaterThanOrEqualTo(String value) {
            addCriterion("RegionName >=", value, "regionname");
            return (Criteria) this;
        }

        public Criteria andRegionnameLessThan(String value) {
            addCriterion("RegionName <", value, "regionname");
            return (Criteria) this;
        }

        public Criteria andRegionnameLessThanOrEqualTo(String value) {
            addCriterion("RegionName <=", value, "regionname");
            return (Criteria) this;
        }

        public Criteria andRegionnameLike(String value) {
            addCriterion("RegionName like", value, "regionname");
            return (Criteria) this;
        }

        public Criteria andRegionnameNotLike(String value) {
            addCriterion("RegionName not like", value, "regionname");
            return (Criteria) this;
        }

        public Criteria andRegionnameIn(List<String> values) {
            addCriterion("RegionName in", values, "regionname");
            return (Criteria) this;
        }

        public Criteria andRegionnameNotIn(List<String> values) {
            addCriterion("RegionName not in", values, "regionname");
            return (Criteria) this;
        }

        public Criteria andRegionnameBetween(String value1, String value2) {
            addCriterion("RegionName between", value1, value2, "regionname");
            return (Criteria) this;
        }

        public Criteria andRegionnameNotBetween(String value1, String value2) {
            addCriterion("RegionName not between", value1, value2, "regionname");
            return (Criteria) this;
        }

        public Criteria andParentregioncodeIsNull() {
            addCriterion("ParentRegionCode is null");
            return (Criteria) this;
        }

        public Criteria andParentregioncodeIsNotNull() {
            addCriterion("ParentRegionCode is not null");
            return (Criteria) this;
        }

        public Criteria andParentregioncodeEqualTo(String value) {
            addCriterion("ParentRegionCode =", value, "parentregioncode");
            return (Criteria) this;
        }

        public Criteria andParentregioncodeNotEqualTo(String value) {
            addCriterion("ParentRegionCode <>", value, "parentregioncode");
            return (Criteria) this;
        }

        public Criteria andParentregioncodeGreaterThan(String value) {
            addCriterion("ParentRegionCode >", value, "parentregioncode");
            return (Criteria) this;
        }

        public Criteria andParentregioncodeGreaterThanOrEqualTo(String value) {
            addCriterion("ParentRegionCode >=", value, "parentregioncode");
            return (Criteria) this;
        }

        public Criteria andParentregioncodeLessThan(String value) {
            addCriterion("ParentRegionCode <", value, "parentregioncode");
            return (Criteria) this;
        }

        public Criteria andParentregioncodeLessThanOrEqualTo(String value) {
            addCriterion("ParentRegionCode <=", value, "parentregioncode");
            return (Criteria) this;
        }

        public Criteria andParentregioncodeLike(String value) {
            addCriterion("ParentRegionCode like", value, "parentregioncode");
            return (Criteria) this;
        }

        public Criteria andParentregioncodeNotLike(String value) {
            addCriterion("ParentRegionCode not like", value, "parentregioncode");
            return (Criteria) this;
        }

        public Criteria andParentregioncodeIn(List<String> values) {
            addCriterion("ParentRegionCode in", values, "parentregioncode");
            return (Criteria) this;
        }

        public Criteria andParentregioncodeNotIn(List<String> values) {
            addCriterion("ParentRegionCode not in", values, "parentregioncode");
            return (Criteria) this;
        }

        public Criteria andParentregioncodeBetween(String value1, String value2) {
            addCriterion("ParentRegionCode between", value1, value2, "parentregioncode");
            return (Criteria) this;
        }

        public Criteria andParentregioncodeNotBetween(String value1, String value2) {
            addCriterion("ParentRegionCode not between", value1, value2, "parentregioncode");
            return (Criteria) this;
        }

        public Criteria andGradeIsNull() {
            addCriterion("Grade is null");
            return (Criteria) this;
        }

        public Criteria andGradeIsNotNull() {
            addCriterion("Grade is not null");
            return (Criteria) this;
        }

        public Criteria andGradeEqualTo(Integer value) {
            addCriterion("Grade =", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotEqualTo(Integer value) {
            addCriterion("Grade <>", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeGreaterThan(Integer value) {
            addCriterion("Grade >", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeGreaterThanOrEqualTo(Integer value) {
            addCriterion("Grade >=", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeLessThan(Integer value) {
            addCriterion("Grade <", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeLessThanOrEqualTo(Integer value) {
            addCriterion("Grade <=", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeIn(List<Integer> values) {
            addCriterion("Grade in", values, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotIn(List<Integer> values) {
            addCriterion("Grade not in", values, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeBetween(Integer value1, Integer value2) {
            addCriterion("Grade between", value1, value2, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotBetween(Integer value1, Integer value2) {
            addCriterion("Grade not between", value1, value2, "grade");
            return (Criteria) this;
        }

        public Criteria andDatacreatetimeIsNull() {
            addCriterion("DataCreateTime is null");
            return (Criteria) this;
        }

        public Criteria andDatacreatetimeIsNotNull() {
            addCriterion("DataCreateTime is not null");
            return (Criteria) this;
        }

        public Criteria andDatacreatetimeEqualTo(Date value) {
            addCriterion("DataCreateTime =", value, "datacreatetime");
            return (Criteria) this;
        }

        public Criteria andDatacreatetimeNotEqualTo(Date value) {
            addCriterion("DataCreateTime <>", value, "datacreatetime");
            return (Criteria) this;
        }

        public Criteria andDatacreatetimeGreaterThan(Date value) {
            addCriterion("DataCreateTime >", value, "datacreatetime");
            return (Criteria) this;
        }

        public Criteria andDatacreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("DataCreateTime >=", value, "datacreatetime");
            return (Criteria) this;
        }

        public Criteria andDatacreatetimeLessThan(Date value) {
            addCriterion("DataCreateTime <", value, "datacreatetime");
            return (Criteria) this;
        }

        public Criteria andDatacreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("DataCreateTime <=", value, "datacreatetime");
            return (Criteria) this;
        }

        public Criteria andDatacreatetimeIn(List<Date> values) {
            addCriterion("DataCreateTime in", values, "datacreatetime");
            return (Criteria) this;
        }

        public Criteria andDatacreatetimeNotIn(List<Date> values) {
            addCriterion("DataCreateTime not in", values, "datacreatetime");
            return (Criteria) this;
        }

        public Criteria andDatacreatetimeBetween(Date value1, Date value2) {
            addCriterion("DataCreateTime between", value1, value2, "datacreatetime");
            return (Criteria) this;
        }

        public Criteria andDatacreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("DataCreateTime not between", value1, value2, "datacreatetime");
            return (Criteria) this;
        }

        public Criteria andDatalastchangetimeIsNull() {
            addCriterion("DataLastChangeTime is null");
            return (Criteria) this;
        }

        public Criteria andDatalastchangetimeIsNotNull() {
            addCriterion("DataLastChangeTime is not null");
            return (Criteria) this;
        }

        public Criteria andDatalastchangetimeEqualTo(Date value) {
            addCriterion("DataLastChangeTime =", value, "datalastchangetime");
            return (Criteria) this;
        }

        public Criteria andDatalastchangetimeNotEqualTo(Date value) {
            addCriterion("DataLastChangeTime <>", value, "datalastchangetime");
            return (Criteria) this;
        }

        public Criteria andDatalastchangetimeGreaterThan(Date value) {
            addCriterion("DataLastChangeTime >", value, "datalastchangetime");
            return (Criteria) this;
        }

        public Criteria andDatalastchangetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("DataLastChangeTime >=", value, "datalastchangetime");
            return (Criteria) this;
        }

        public Criteria andDatalastchangetimeLessThan(Date value) {
            addCriterion("DataLastChangeTime <", value, "datalastchangetime");
            return (Criteria) this;
        }

        public Criteria andDatalastchangetimeLessThanOrEqualTo(Date value) {
            addCriterion("DataLastChangeTime <=", value, "datalastchangetime");
            return (Criteria) this;
        }

        public Criteria andDatalastchangetimeIn(List<Date> values) {
            addCriterion("DataLastChangeTime in", values, "datalastchangetime");
            return (Criteria) this;
        }

        public Criteria andDatalastchangetimeNotIn(List<Date> values) {
            addCriterion("DataLastChangeTime not in", values, "datalastchangetime");
            return (Criteria) this;
        }

        public Criteria andDatalastchangetimeBetween(Date value1, Date value2) {
            addCriterion("DataLastChangeTime between", value1, value2, "datalastchangetime");
            return (Criteria) this;
        }

        public Criteria andDatalastchangetimeNotBetween(Date value1, Date value2) {
            addCriterion("DataLastChangeTime not between", value1, value2, "datalastchangetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CA_Region
     *
     * @mbggenerated do_not_delete_during_merge Thu Mar 02 14:53:09 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CA_Region
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}