package com.yunxin.entity;

import java.util.Date;

public class CaRegion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Region.RegionCode
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private String regioncode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Region.RegionName
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private String regionname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Region.ParentRegionCode
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private String parentregioncode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Region.Grade
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private Integer grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Region.DataCreateTime
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private Date datacreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CA_Region.DataLastChangeTime
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    private Date datalastchangetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Region.RegionCode
     *
     * @return the value of CA_Region.RegionCode
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public String getRegioncode() {
        return regioncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Region.RegionCode
     *
     * @param regioncode the value for CA_Region.RegionCode
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setRegioncode(String regioncode) {
        this.regioncode = regioncode == null ? null : regioncode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Region.RegionName
     *
     * @return the value of CA_Region.RegionName
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public String getRegionname() {
        return regionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Region.RegionName
     *
     * @param regionname the value for CA_Region.RegionName
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setRegionname(String regionname) {
        this.regionname = regionname == null ? null : regionname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Region.ParentRegionCode
     *
     * @return the value of CA_Region.ParentRegionCode
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public String getParentregioncode() {
        return parentregioncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Region.ParentRegionCode
     *
     * @param parentregioncode the value for CA_Region.ParentRegionCode
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setParentregioncode(String parentregioncode) {
        this.parentregioncode = parentregioncode == null ? null : parentregioncode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Region.Grade
     *
     * @return the value of CA_Region.Grade
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Region.Grade
     *
     * @param grade the value for CA_Region.Grade
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Region.DataCreateTime
     *
     * @return the value of CA_Region.DataCreateTime
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public Date getDatacreatetime() {
        return datacreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Region.DataCreateTime
     *
     * @param datacreatetime the value for CA_Region.DataCreateTime
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setDatacreatetime(Date datacreatetime) {
        this.datacreatetime = datacreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CA_Region.DataLastChangeTime
     *
     * @return the value of CA_Region.DataLastChangeTime
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public Date getDatalastchangetime() {
        return datalastchangetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CA_Region.DataLastChangeTime
     *
     * @param datalastchangetime the value for CA_Region.DataLastChangeTime
     *
     * @mbggenerated Thu Mar 02 14:53:09 CST 2017
     */
    public void setDatalastchangetime(Date datalastchangetime) {
        this.datalastchangetime = datalastchangetime;
    }
}